### ISSUE TITLE
[BETA] Nombre de réponse sur forum

### ISSUE THREAD

**Issue by SwithFr** [Grafikart/Grafikart.fr#108]
Le message initial sur un forum est compté comme une réponse. 

ex on voit "2 réponses" mais 1 seule visible : 

![image](https://user-images.githubusercontent.com/4257500/100068668-1d53a780-2e38-11eb-8bac-b6d9367ec781.png)

D'ailleurs le nombre n'est pas incrémenté après avoir posté une réponse. (Mais au rechargement de la page oui)

**Comment by Grafikart** [comment]
J'ai l'impression que c'est seulement sur les vieux sujet non ? Peut être une erreur à l'import

**Comment by SwithFr** [comment]
Ah j'ai pas regardé, c'est possible ! 
Mais pour le coup j'ai testé sur des sujets en page 1 puisqu'il n'y a pas de pagination ^^ donc ça doit pas non plus être des très vieux sujets :/

**Comment by magnin** [comment]
Je remonte ça : en fait tous les messages sont comptabilisés en double dans le compteur de réponse.
Sur un topic mais aussi sur /forum :
![image](https://user-images.githubusercontent.com/11465943/104107989-3cf83f80-52c1-11eb-8ccf-9c7e593b1575.png)
