### ISSUE TITLE
[BETA] Partager sur facebook

### ISSUE THREAD

**Issue by SwithFr** [Grafikart/Grafikart.fr#110]
Le partage sur twitter d'un tuto semble ok mais facebook nope : 

![image](https://user-images.githubusercontent.com/4257500/100069454-137e7400-2e39-11eb-927d-1917aa6190a9.png)

Problème d'app sans doute ?

**Comment by Grafikart** [comment]
C'est à cause du htpasswd. Cela marche si je le retire.
