### ISSUE TITLE
[BETA] (idée) tutoriels par niveau

### ISSUE THREAD

**Issue by SwithFr** [Grafikart/Grafikart.fr#112]
Au même titre qu'on a la page https://beta.grafikart.fr/tutoriels/premium (d'ailleurs il manque un lien pour y arriver)
Ça serait d'avoir un lien sur les badges de niveau "débutant"... sous les vidéos qui mène au listing des tutos du dit niveau.

**Comment by Grafikart** [comment]
Le filtre a été mis en place .
