### ISSUE TITLE
[BETA] Déblocage badge commentaires

### ISSUE THREAD

**Issue by SwithFr** [Grafikart/Grafikart.fr#115]
Pas reçu le badge des 100 commentaires :'(
J'avais celui des 50 + 50 nouveaux commentaires j'ai rien reçu.

**EDIT** il a bien été débloqué (mais pas vue tout de suite, cache ?) par contre j'ai pas eu l'alerte comme quoi il avait été débloqué.

**Comment by Grafikart** [comment]
Je pense que cela est lié au problème de mercure / messenger qui ne marche pas. Je ferme
