### ISSUE TITLE
[BETA] L'envoi des Mails ne fonctionne pas

### ISSUE THREAD

**Issue by rudstone** [Grafikart/Grafikart.fr#125]
Lorsque je souhaite créer un compte, je ne reçois pas de mail voulant confirmer mon compte...

**Comment by Grafikart** [comment]
Tu peux retenter ? normalement le problème a été résolu.

**Comment by rudstone** [comment]
Ca fonctionne !

**Comment by rudstone** [comment]
De nouveau le problème...

**Comment by endermctv** [comment]
moi je reçois le mail 12 heures après qu'il me dit qu'il l'a envoyé
