### ISSUE TITLE
[BETA] Problème de style sur la page tuto single

### ISSUE THREAD

**Issue by betaWeb** [Grafikart/Grafikart.fr#127]
Salut Graf',

Le contenu du site se stack sur la gauche sous certaines conditions. Visiblement un souci au niveau de la classe `.container` (cf capture ci-dessous). Le style est dans le head, il a l'ait d'être auto-généré, à moins que ça soit toi @Grafikart qui l'ai mis là ?

![image](https://user-images.githubusercontent.com/13481208/100389916-117e0600-302f-11eb-8ecf-cfd6a257529f.png)

Voici le workflow pour reproduire le bug :
 -> Page d'accueil
 -> Cliquer sur "Se connecter"
 -> Puis sur le bouton "Se connecter avec Facebook" -> Erreur 500 (normal) -> go back
 -> Page tutoriels
 -> Cliquer sur un tuto (n'importe le quel) ou même revenir à la page d'accueil (cf capture ci-dessous)

Mon env :
 -> Ubuntu 20.04.1 LTS x86_64 (5.4.0-54-generic)
 -> Chrome 87.0.4280.66 (Build officiel) (64 bits)
 -> Résolution 1794 x 593 (DPI 137) (résolution originale 2560 x 1080)

![2020-11-26-21-29-beta grafikart fr](https://user-images.githubusercontent.com/13481208/100389737-79801c80-302e-11eb-863b-46c823cfc786.png)

**Comment by Grafikart** [comment]
J'imagine que tu as eu l'erreur quand tu reviens d'une page d'erreur. J'ai résolu le layout de la page d'erreur donc le problème ne devrait plus se reproduire (tu confirme? )

**Comment by betaWeb** [comment]
Je confirme.
