### ISSUE TITLE
[BETA] Impossible de lier mon compte github

### ISSUE THREAD

**Issue by Hypario** [Grafikart/Grafikart.fr#132]
Lorsque je tente de lier mon compte GitHub, j'atterris sur la page 404 de GitHub

**Comment by Hypario** [comment]
Il en va de même pour un compte Google.

En revanche pour Facebook, on atterrit sur la page 404 de la beta de grafikart.fr

**Comment by rudstone** [comment]
Apparemment, c'est normal pour le moment ;)

**Comment by Hypario** [comment]
Update : la connexion via facebook / google fonctionne, on attend encore pour github

**Comment by qbtl** [comment]
La connexion via GitHub fonctionne mais nous renvoie vers grafikart.fr au lieu de beta.grafikart.fr

**Comment by Grafikart** [comment]
Github ne me laisse pas associer plusieurs domaine donc ça ne marchera que lors de la mise en ligne :(
