### ISSUE TITLE
Attribut ID en doublon

### ISSUE THREAD

**Issue by Mcdostone** [Grafikart/Grafikart.fr#136]
ID en doublon sur `<youtube-player>` et `<premium-player>`
- ligne 49, 54
- ligne 60, 65

https://github.com/Grafikart/Grafikart.fr/blob/e8dbc9f3cc53be48c6bed5b470ed8e93f2563673/templates/courses/show.html.twig#L49-L65

**Comment by Grafikart** [comment]
Les 2 éléments ne sont pas affiché en même temps sur la page (if else) donc cela n'est pas problématique non ?

**Comment by Mcdostone** [comment]
Mon explication est peut être imprécise:
oui tout a fait, les deux éléments ne sont pas affichés en même temps. Cependant, tu déclares 2 IDs sur ces éléments: 

```html
<youtube-player
          id="course-{{ course.id }}"                             <!-- ICI -->
          video="{{ course.youtubeId }}"
          poster="{{ image_url(course.image, 1330, 750) }}"
          button="#chapter{{ course.id }} play-button"
          duration="{{ course.duration | duration }}"
          id="coursePlayer"                                       <!-- ET LA -->
          class="shadow">
</youtube-player>
```

même chose sur le `<premium-player />`
