### ISSUE TITLE
DESIGN : Single Tutoriel

### ISSUE THREAD

**Issue by Grafikart** [Grafikart/Grafikart.fr#14]

**Comment by SwithFr** [comment]
Sur cette page, il serait sympa d'avoir en plus des **technologies abordées**, une suggestion de tutoriels soit sur le thème, soit les technos, etc.

**Comment by betaWeb** [comment]
Salut @Grafikart,

Une petite fonctionnalité qui pourrait être sympa (sur les formations également d'ailleurs) : lorsque qu'une vidéo se termine, afficher un bouton `Vidéo suivante` en filigrane. Ça pourrait être pertinent sur les formations je pense.
Ou encore imaginer, dans le cas d'un tutoriel, en plus de ce bouton, une sélection de vidéos dont les technos ont rapport (un peu comme les suggestions sut YT en somme).
