### ISSUE TITLE
[BETA] Ça tombe sur une page 404 Github quand on essaie d'y aller

### ISSUE THREAD

**Issue by L14ms111** [Grafikart/Grafikart.fr#146]
Donc en gros quand on veut lier ou connecter avec GitHub ça nous tombe sur une page 404 GitHub.

**Comment by endermctv** [comment]
Oui, c'est normal, ça fait la même avec facebook et google : étant donné que c'est a béta, il va pas mettre de lien réels.

**Comment by Hypario** [comment]
duplicata de #132

**Comment by Grafikart** [comment]
Cette fonction ne sera disponible qu'au moment de la mise en ligne car github n'autorise pas plusieurs oauth callback :(
