### ISSUE TITLE
[BETA] Problème de responsive sur Iphone 12 Pro

### ISSUE THREAD

**Issue by Fredxd** [Grafikart/Grafikart.fr#149]
Hello, je te report quelques issues que j'ai eu sur la beta au premier coup d'oeil.
Il n'y a pas que des issues de responsive mais comme la majorité c'est du responsive, j'ai tout mis dedans ;)

- Device: Iphone 12 pro
- Browser: Chrome

### Menu principal

- Les liens "S'inscrire" et "Se connecter" rendent pas terrible

![Menu principal](https://user-images.githubusercontent.com/4354248/103239659-8bffb580-494e-11eb-8b9f-e9e500da2d65.PNG)

### Blog

- Le contenu du 1er bloc ne se "fit" pas au container. Ce qui est étrange étant donné que les autres contenus se "fit" bien.

![Blog](https://user-images.githubusercontent.com/4354248/103239898-2829bc80-494f-11eb-889b-760bfa754df0.PNG)

- Le contenu déborde.

![Blog2](https://user-images.githubusercontent.com/4354248/103240161-d2094900-494f-11eb-98ac-21a395a03e08.PNG)

### Forum

- Le titre du sujet ne prend pas toute la place qu'il a de disponible.

![Forum](https://user-images.githubusercontent.com/4354248/103240001-658e4a00-494f-11eb-8067-2a711c32cd3f.PNG)

- Il est dommage de devoir scroll en bas de la liste des sujets afin de pouvoir créer un nouveau sujet. Idem concernant les catégories.

![Forum2](https://user-images.githubusercontent.com/4354248/103240081-979fac00-494f-11eb-8741-3ae5ed0579fa.PNG)

### Formation

- Le bloc est vide quand il n'y a pas de "Liens" ou de "Pré-requis"

![Formation](https://user-images.githubusercontent.com/4354248/103240264-21e81000-4950-11eb-9c10-d6b178fb658c.PNG)

### Footer

- Le bloc "Mes derniers tweets" quand il n'y a pas de tweets récents.

![Footer](https://user-images.githubusercontent.com/4354248/103240377-768b8b00-4950-11eb-9273-19bbda6c806e.PNG)

**Comment by Rom1-J** [comment]
J'ajouterais de plus : 
Impossible d'accéder à "Toutes les notifications" en mode portrait (iPhone XR)

https://user-images.githubusercontent.com/25200594/104158970-cb1e1400-53ee-11eb-9a54-7db021859473.MP4

**Comment by Grafikart** [comment]
Fermé par erreur à cause d'une MR ;)

**Comment by Grafikart** [comment]
Si il reste des choses qui ne vont pas je préfère une nouvelle issue.
