### ISSUE TITLE
[BETA] Page 404

### ISSUE THREAD

**Issue by rudstone** [Grafikart/Grafikart.fr#150]
Lorsque nous sommes connecté au site, arrivé sur la page 404 du site, cela nous définis comme n'étant pas connecté.

![IFczJxn](https://user-images.githubusercontent.com/70549774/103367722-21718580-4ac6-11eb-978f-d00e42bfd648.png)

**Comment by Grafikart** [comment]
C'est une limitation de symfony et je ne peux rien y faire malheureusement :(
Cette issue pour avoir une référence : https://github.com/symfony/symfony/issues/8414
