### ISSUE TITLE
[BETA] Déblocage d'un badge

### ISSUE THREAD

**Issue by rudstone** [Grafikart/Grafikart.fr#151]
Lorsque nous souhaitons débloquer le badge "lochness" en tapant dans la console JS lochness();, le badge ne se débloque pas et indique une page 403.

**Comment by endermctv** [comment]
Je pense que tu doit être connecté car moi je ne suis pas connecté et il n'y a pas d'erreurs.

![](https://zupimages.net/up/21/01/323k.png)

**Comment by Grafikart** [comment]
@rudstone Peux tu me dire si tu étais connecté au moment de l'erreur ?

**Comment by rudstone** [comment]
J'était connecté effectivement.
![2021-01-08 00_05_33-Window](https://user-images.githubusercontent.com/70549774/103954824-51173200-5145-11eb-80a5-ca4a02ce8a2c.png)

**Comment by rudstone** [comment]
Le badge Lochness a été retiré...

**Comment by endermctv** [comment]
😢

**Comment by Grafikart** [comment]
Non il a été changé de nom ;)

**Comment by rudstone** [comment]
![2021-01-11 14_55_09-Microsoft Store](https://user-images.githubusercontent.com/70549774/104190948-2109b080-541d-11eb-94bb-96fbc225e027.png)

**Comment by endermctv** [comment]
OUF ! Merci 👍

**Comment by Grafikart** [comment]
Tu peux me montrer ce qui se passe quand tu tape grafikart.USER ?

**Comment by qbtl** [comment]
Quand on tape grafikart.USER on nous retourne une valeur dans la console

![grafikart.USER](https://user-images.githubusercontent.com/54680442/104283116-5b705d80-54b0-11eb-8924-b19a44ce060f.png)
