### ISSUE TITLE
[BETA] problème typo Recherche

### ISSUE THREAD

**Issue by Romaixn** [Grafikart/Grafikart.fr#154]
Lorsque l'on recherche "Symfony" (par exemple) il y a un problème de typo avec le â de tâches. Pareil avec "Créer un thème WordPress" qui s'affiche comme "Cr'eer un th`eme WordPress"

![image](https://user-images.githubusercontent.com/18333296/103875122-51c2b080-50d2-11eb-8a9c-4dc5917ff105.png)

**Comment by Grafikart** [comment]
Bien vu, c'était une erreur avec la version 0.17 de typesense
