### ISSUE TITLE
Forum Show Route (Clique sur Avatar)

### ISSUE THREAD

**Issue by ralal01** [Grafikart/Grafikart.fr#156]
Sur beta.grafikart.fr 

Lorsqu'on clique sur le l'avatar d'un forum, cela envoie un 500; surement les requirement dans la route? 

Et aussi les tutoriels , les commentaires ne se chargent pas en scrollant ou pas du tout; on voit juste le nombre de comments.

**Comment by Grafikart** [comment]
C'est corrigé merci !
