### ISSUE TITLE
[BETA] (Safari 14) Les filtres de la page formation ne rafraichissent pas la page

### ISSUE THREAD

**Issue by bastiennicoud** [Grafikart/Grafikart.fr#157]
Sur la [page des formations](https://beta.grafikart.fr/tutoriels) lors le la selection d'un niveau ou d'une technologie, la page n'est pas rafraichie. (Problème survenu uniquement sur Safari).

https://user-images.githubusercontent.com/24266957/104062325-8b8ed680-51fa-11eb-913f-fbec645a93b1.mov

Sur la [page blog](https://beta.grafikart.fr/blog/category/bonnes-pratiques) un select du même genre fonctionne quant à lui.

**Comment by Grafikart** [comment]
Ce problème a été corrigé en corrigeant un autre problème ;)

**Comment by bastiennicoud** [comment]
J'ai refais un tour... décidément safari est plein de surprises.

Maintenant le bug du rechargement de la page semble bien corrigé, quant on sélectionne un element dans les select la page se met bien a jour... mais le *select lui même ne se met pas a jour.*

https://user-images.githubusercontent.com/24266957/104507944-cbcdca80-55e7-11eb-948a-76265479a4a4.mov
