### ISSUE TITLE
[BETA] page profil utilisateur en venant du forum

### ISSUE THREAD

**Issue by quentinGeeraert** [Grafikart/Grafikart.fr#158]
Erreur 500 quand on clique sur le nom de l'auteur d'un post depuis le forum : [https://beta.grafikart.fr/profil/%7Bid:%5Cd+%7D?id=117729](https://beta.grafikart.fr/profil/%7Bid:%5Cd+%7D?id=117729)

**Comment by Grafikart** [comment]
corrigé !
