### ISSUE TITLE
[BETA] Manque image ou dossier ICONS

### ISSUE THREAD

**Issue by maxiweb-nouvelle-caledonie** [Grafikart/Grafikart.fr#161]
![image](https://user-images.githubusercontent.com/77216970/104112254-88056780-5340-11eb-92db-bee59574a289.png)

Il manque certaines images sur la page /tutoriels
apparemment le dossier https://beta.grafikart.fr/uploads/icons/

**Comment by Grafikart** [comment]
Je gérerais l'envoie des icones au moment de la mise en ligne
