### ISSUE TITLE
[BETA] Konami code

### ISSUE THREAD

**Issue by Cyberdump** [Grafikart/Grafikart.fr#162]
Je suis connecté, et lorsque je fait le Konami code il y a cette erreur dans la console : 
XHR POST https://beta.grafikart.fr/api/badges/gamer/unlock [HTTP/2 403 Forbidden 55ms]
Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

![image](https://user-images.githubusercontent.com/55019004/104119547-4d93ce80-5330-11eb-91aa-481f85a234e7.png)

**Comment by rudstone** [comment]
![2021-01-10 17_17_55-Window](https://user-images.githubusercontent.com/70549774/104128450-d9751d00-5367-11eb-926e-509554aa6595.png)

**Comment by endermctv** [comment]
@rudstone c'est en méthode POST qu'il faut le faire (tu est en GET).

**Comment by rudstone** [comment]
Même erreur également ;)
