### ISSUE TITLE
[BETA] icon du theme-switcher

### ISSUE THREAD

**Issue by ComFoxx** [Grafikart/Grafikart.fr#167]
Au chargement de la page on voit les icons du theme-switcher en haut à gauche de la page en position: absolute; top: 5px; left: 5px; car la classe form-switch et son position: relative; ne s'ajoute au parent qu'au chargement du web component.

![image](https://user-images.githubusercontent.com/17570186/104137324-13601680-539c-11eb-88e6-53da9eae5eb6.png)

Avant le chargement du web component :

![image](https://user-images.githubusercontent.com/17570186/104137421-c6c90b00-539c-11eb-8dcc-9c330ab746d0.png)

Après le chargement du web component :

![image](https://user-images.githubusercontent.com/17570186/104137425-d0eb0980-539c-11eb-8b28-ce524ab1ea21.png)

**Comment by louia** [comment]
Ce soucis est présent sur Safari mais il est persistant. ![image](https://user-images.githubusercontent.com/33846211/104224524-6346e800-5445-11eb-8ed3-2846dbf270e0.png)￼

![image](https://user-images.githubusercontent.com/33846211/104224540-68a43280-5445-11eb-9f8a-01dddade2004.png)

**Comment by ComFoxx** [comment]
Oui sur Safari le switch ne charge même pas : #160
Ce qui explique que ça persiste
