### ISSUE TITLE
[BETA] Spam requete pour les svg

### ISSUE THREAD

**Issue by Rom1-J** [Grafikart/Grafikart.fr#175]
Quand on hover un contenu avec svg (ex: sur notre page profil pour faire apparaitre le "editer" sur l'avatar), le site execute 2 requetes, une a l'hover et une une fois unhover, et ce a chaque fois
cf video 

https://user-images.githubusercontent.com/25200594/104194459-aa22e680-5421-11eb-86aa-14bc2430e988.mp4

**Comment by stromcon** [comment]
N'arrive pas à reproduire sur mon poste

**Comment by Rom1-J** [comment]
Je n'arrive plus a reproduire ce bug



La derniere fois qu'il s'est produit :

Navigateur: Google Chrome | 89.0.4381.6 (Official Build) dev (64-bit)
Systeme: Arch Linux Linux 5.10.6-arch1-1
Extensions: Augury | Chrome extension source viewer | Colorzilla | Cookie Editor | Dark reader | Full page screen caputre | Javascript & css code beautifier | Jetbrains Toolbox Extension | JSON Formatter | ModHeader | React Dev Tools | RestMan | Styler | uBlock Origin | Vue.js devtools | Wappalyzer | WhatFont

**Comment by Rom1-J** [comment]
Malgré tous les efforts pour essayer de reproduire ca, aucun résultat...

Je ferme donc cette issue
