### ISSUE TITLE
[BETA] Upload image sur un profil qui n'est pas le notre

### ISSUE THREAD

**Issue by Brigat0** [Grafikart/Grafikart.fr#176]
En allant sur l'avatar d'un profil on peut afficher le menu contextuel pour upload une nouvelle image.

![Screenshot_55](https://user-images.githubusercontent.com/48072357/104218816-91c0c500-543d-11eb-8994-63a2b4d9e09a.png)

**Comment by ComFoxx** [comment]
Duplicate of #164
