### ISSUE TITLE
[BETA] Profile thème switch mobile

### ISSUE THREAD

**Issue by FoxxenD** [Grafikart/Grafikart.fr#184]
Bonjour, sur mobile (navigateur chrome), lorsque l'on va sur son profile, l'option pour changer de thème n'apparait pas. Il faut modifier une fois les préférences pour qu'il s'affiche ou bien actualiser la page

https://user-images.githubusercontent.com/32935159/104242421-6ea70d00-545f-11eb-8524-e0912d778167.mp4

**Comment by Grafikart** [comment]
Je n'arrive pas à produire le bug, tu peux m'en dire plus sur ton environnement.

**Comment by FoxxenD** [comment]
Actuellement le soucis est également sur la version PC (chrome toujours). Je remarque que cela marche lorsque l'on vient juste de se connecter, mais par la suite, le bug arrive
Pour la version de chrome sur PC : Version 87.0.4280.141 (Build officiel) (64 bits)
J'ai le soucis sur Opéra, Edge, Firefox (PC)

https://user-images.githubusercontent.com/32935159/104357482-8d63dd00-550d-11eb-96f7-3833a94c75ec.mp4

**Comment by endermctv** [comment]
@FoxxenD moi ça marche très bien

**Comment by FoxxenD** [comment]
Bonjour, j'ai tester aujourd'hui et pas possible de reproduire le problème
Peut-être que le problème était le même que pour cette issue [https://github.com/Grafikart/Grafikart.fr/issues/229](https://github.com/Grafikart/Grafikart.fr/issues/229) J'ai oublier de regarder la console lors des essais

**Comment by Grafikart** [comment]
Le problème a été effectivement corrigé par le #229
