### ISSUE TITLE
[BETA] Select profil mauvaise couleur

### ISSUE THREAD

**Issue by qbtl** [Grafikart/Grafikart.fr#190]
Bonjour, dans le profil en thème dark le select des pays ne s'affiche pas dans la bonne couleur.

![Select page profil](https://user-images.githubusercontent.com/54680442/104282539-8312f600-54af-11eb-8f19-bb5ce19f3d6b.jpg)

**Comment by Grafikart** [comment]
Quel navigateur ?

**Comment by qbtl** [comment]
Sur chrome la dernière version

**Comment by ComFoxx** [comment]
Pareil sur la page premium

![image](https://user-images.githubusercontent.com/17570186/104348602-34427c00-5502-11eb-9e2e-6dff8d710955.png)

**Comment by ComFoxx** [comment]
Le problème vient de l'ajout de la flèche avec le `background` qui réécrit le `background` de la couleur
