### ISSUE TITLE
[BETA] Erreur Serveur (TooManyEmailChangeException) edition email dans profil

### ISSUE THREAD

**Issue by Rom1-J** [Grafikart/Grafikart.fr#197]
Quand on décide de changer notre adresse mail dans le profile, la premiere fois marche avec la notification en haut a droite (qui au passage selon moi est beaucoup trop rapide, pas le temps de la lire), mais quand on décide de changer a nouveau, Erreur serveur

cf
![image](https://user-images.githubusercontent.com/25200594/104315625-87ed9f00-54db-11eb-91d2-8646ce80a227.png)
![image](https://user-images.githubusercontent.com/25200594/104315670-93d96100-54db-11eb-87f5-9df1d4cf241e.png)

**Comment by Grafikart** [comment]
Le message a été figé
