### ISSUE TITLE
[BETA] Erreur Serveur (TypeError) route auth_password_reset_confirm

### ISSUE THREAD

**Issue by Rom1-J** [Grafikart/Grafikart.fr#199]
Quand on se rend (en tant qu'utilisateur connecté ou non) sur https://beta.grafikart.fr/password/new/1/azeaze, on obtiens une Erreur Serveur à la place de je ne sais quelle erreur mais probablement pas celle ci :sweat_smile: 

cf 
![image](https://user-images.githubusercontent.com/25200594/104319568-5677d200-54e1-11eb-8ca5-3393f88c3999.png)
![image](https://user-images.githubusercontent.com/25200594/104319602-64c5ee00-54e1-11eb-8541-e090732e4ff4.png)

**Comment by endermctv** [comment]
comment t'as accedé à http://test.grafikart.fr:8000 ?

**Comment by Rom1-J** [comment]
> comment t'as accedé à http://test.grafikart.fr:8000 ?

en téléchargeant le projet, setupant docker et ajoutant la regle test.grafikart.fr vers 127.0.0.1 dans mon /etc/hosts

**Comment by endermctv** [comment]
ah ok merci
