### ISSUE TITLE
DESIGN : Carte Formation

### ISSUE THREAD

**Issue by Grafikart** [Grafikart/Grafikart.fr#2]
L'objectif est de créer une carte pour représenter une formation. Cette carte serait repris dans les différents listings. Pour moi les informations importantes sont 

- La technologie / sujet de la formation
- Le nombre de vidéo / chapitres
- La durée de la formation
- Le niveau nécessaire pour suivre la formation (est-ce que si je débute dans la techno je peux suivre la formation ?)

**Comment by Grafikart** [comment]
**Première version** 

![Card simple](https://user-images.githubusercontent.com/395137/66840018-a925af80-ef67-11e9-9ad4-bff48fc95919.png)

**Comment by rebelor** [comment]
Avec un peu plus de contraste... peut être ajouter aussi un petit drapeau informant de contenus "premium" dans la formation ...?
![image](https://user-images.githubusercontent.com/2782011/67134122-b44f3880-f210-11e9-8837-e144f393ca33.png)

**Comment by Sh1n1x** [comment]
Hello Graf',

Petite contribution de ma part à voir ce que tu en penses.

Je suis parti de l'idée que les tutos & formations ont les mêmes "cards" mais avec des tags différents.

![image](https://user-images.githubusercontent.com/1647512/67143289-46375f80-f26a-11e9-9163-704fe89ae760.png)

**Comment by Fredkiss3** [comment]
> Hello Graf',
> 
> Petite contribution de ma part à voir ce que tu en penses.
> 
> Je suis parti de l'idée que les tutos & formations ont les mêmes "cards" mais avec des tags différents.
> 
> ![image](https://user-images.githubusercontent.com/1647512/67143432-a8449480-f26b-11e9-989c-e62eab831a8c.png)

Le Design est plutôt cool, mais il semble un peu trop compact
