### ISSUE TITLE
[BETA] Menu sur mobile

### ISSUE THREAD

**Issue by makamo** [Grafikart/Grafikart.fr#204]
Bonjour 

Sur mobile quand le menu est ouvert. Si on effectue un scroll rapide pour aller plus bas.

Le menu se décale vers le haut et ca laisse un espace en bas 
![image](https://user-images.githubusercontent.com/1319567/104358530-92f4ff00-54dc-11eb-87c0-63cef928106a.png)

**Comment by Grafikart** [comment]
Le menu reste comme cela ou il récupère sa position après l'effet t?

**Comment by makamo** [comment]
Il reprend sa place ensuite

**Comment by Grafikart** [comment]
tu as d'autres sites web qui ont des overlay full page pour lequel le problème n'apparait pas ?

**Comment by makamo** [comment]
Non effectivement ça ma l'air d'un problème récurent sur les sites avec un menu fullscreen
