### ISSUE TITLE
[BETA] Erreur Serveur (TypeError) changement de mot de passe a vide

### ISSUE THREAD

**Issue by Rom1-J** [Grafikart/Grafikart.fr#208]
## Description
Lorsqu'on décide de changer le mot de passe sur la section édité de notre profile et que, en tant que petit malin, décide aussi de virer les required="required" des 2 inputs pour mot de passe, on obtient une Erreur Serveur

De plus, sur cet input, il n'y a plus les restrictions de longueur du mdp donc on peut aussi choisir un simple espace comme mdp ou bien un qui dépasse les 4096 chars

## Demo
https://user-images.githubusercontent.com/25200594/104424323-82e22b80-557f-11eb-99b8-bde0cf8ff331.mp4

## Erreur
![image](https://user-images.githubusercontent.com/25200594/104424569-d5234c80-557f-11eb-8668-fb5f03246baa.png)

**Comment by Rom1-J** [comment]
Fix via https://github.com/Grafikart/Grafikart.fr/pull/209

**Comment by kl3sk** [comment]
Concernant ce fix sur le live de ce soir.

Tu as mis un `new NotBlank(['normalizer' => 'trim'])` sur le compte que tu n'as pas reporté sur le formulaire d'inscription.

Rien de bien grave, mais la consistance :p
