### ISSUE TITLE
[BETA] Notification forum

### ISSUE THREAD

**Issue by Rom1-J** [Grafikart/Grafikart.fr#213]
## Description
Quand on envoie un message sur un forum, on recoit une notification pour notre propre message

## Demo

https://user-images.githubusercontent.com/25200594/104451589-0e6cb400-55a2-11eb-9222-61288c5b9e9f.mp4

**Comment by endermctv** [comment]
c'était donc toi le faux grafikart...

**Comment by Rom1-J** [comment]
@endermctv eh oui :sweat_smile: mais au final je suis toujours a la recherche d'un moyen d'avoir exactement le meme pseudo pour tenter une intrusion sur /admin

**Comment by ComFoxx** [comment]
De mon côté je reçois également des notifications que je ne devrais pas recevoir - à savoir les siennes - alors que je viens de m'inscrire et que je n'ai aucun rapport avec ce sujet de forum.

![image](https://user-images.githubusercontent.com/17570186/104463483-20eee980-55b2-11eb-9359-4a6aa92a8962.png)

La requête vers mercure est la suivante : `https://beta.grafikart.fr/.well-known/mercure/?topic=/notifications/{channel}&topic=/notifications/user/242168`.
Est-ce normal d'avoir un `{channel}` dedans ?
