### ISSUE TITLE
[BETA] Paypal en anglais

### ISSUE THREAD

**Issue by ComFoxx** [Grafikart/Grafikart.fr#215]
Paypal apparait en anglais.

![image](https://user-images.githubusercontent.com/17570186/104468225-7e396980-55b7-11eb-9122-0bcf39f4b4bf.png)

**Comment by Grafikart** [comment]
Ton system / navigateur est en français ?

**Comment by ComFoxx** [comment]
Mon système est en français, mon navigateur est en français et il accepte l'anglais mais le français est prioritaire.
Le problème vient peut-être de Paypal, il arrive que certains sites ne prennent pas en compte les priorités des langues du navigateur mais paypal.com me redirige vers la version francophone.

**Comment by bnoufel** [comment]
Plop,

Pour moi la page est bien en Français.

Normalement si tu acceptes les cookies (ou que tu scroll tout en bas de la page) tu as une option pour mettre la page en français 
![image](https://user-images.githubusercontent.com/6586577/106337538-ac929680-6291-11eb-8f3f-d34c427f6847.png)

Par contre en navigation privé j'ai bien ce soucis.

Tu peux donner ces informations @ComFoxx ?

*En navigation normale:*

`navigator.language: "en-US"`
`navigator.languages: ["en-US", "en", "fr"]`

*En navigation privée:*

`navigator.language: "en-US"`
`navigator.languages: ["en-US"]`

**Comment by ComFoxx** [comment]
Je n'ai pas ce soucis en navigation normale, avec ces infos : 
navigator.language: "fr"
navigator.languages: ["fr", "fr-FR", "en", "en-US", "und"]

J'ai effectivement ce soucis en navigation privée, mais quand même avec ces infos :
navigator.language: "fr"
navigator.languages: ["fr"]

Dans tous les cas, le problème me semble plus venir de Paypal et non de l'implémentation, ce n'est pas un problème important, en plus on peut toujours changer de langue...

**Comment by bnoufel** [comment]
Yeap, du coup c'est plus strange, sinon dernier petit test, quand tu veux payer par payal si tu check l'URL tu as un params `locale.x` quelle est la valeur ?

Sinon @Grafikart pour "fix" ce soucis sur certains API de liste de country `https://restcountries.eu/rest/v2/` tu peux get la locale en plus du payer et donc forcer la local en fonction du pays.

Mais en soit oui, sans faire ça c'est paypal qui le gère comme ça
![image](https://user-images.githubusercontent.com/6586577/106357146-9540c100-6304-11eb-8639-61badddc8cdd.png)

https://developer.paypal.com/docs/api/reference/locale-codes/

**Comment by Grafikart** [comment]
Pour le coup je préfère laisser paypal s'adapter à la locale du navigateur. Chez moi c'est en français même en privé.
