### ISSUE TITLE
[BETA] Inconsistences dans les titres

### ISSUE THREAD

**Issue by ComFoxx** [Grafikart/Grafikart.fr#218]
Inconsistences dans les titres :
 
- https://beta.grafikart.fr/ `Grafikart | Tutoriels et Formations vidéos sur le développement web | Grafikart` Grafikart deux fois, pareil quand on est connecté : `Grafikart | Dernier tutoriels | Grafikart`

 - https://beta.grafikart.fr/error.html `Title` Oublie de modification du titre

 - https://beta.grafikart.fr/tutoriels/distance-levenshtein-1372 `Tutoriel vidéo Algorithmique : Distance de Levenshtein | Grafikart` Le titre du tutoriel n'est pas directement au début et un onglet a une petite largeur, je verrais plutôt un `Distance de Levenshtein — Algorithmique — Tutoriel vidéo | Grafikart`

 - https://beta.grafikart.fr/forum/33736 `Apprendre HTML | Grafikart` Ici le titre d'un sujet du forum correspond à une autre page du site : https://beta.grafikart.fr/tutoriels/html il faudrait rajouter `Forum` pour bien indiquer qu'il s'agit d'un sujet du forum et non une autre page

 - https://beta.grafikart.fr/tutoriels/javascript-cannot-read-property-1348 `Formation Déboguer son code JavaScript : Cannot read property of null | Grafikart` ici aussi je verrais plutôt un `Cannot read property of null — Déboguer son code JavaScript — Formation | Grafikart` histoire d'avoir le coeur du sujet affiché dans l'onglet

 - https://beta.grafikart.fr/tutoriels?page=4 `Tous les tutoriels, page4 | Grafikart` il manque un espace entre page et le numéro (et je trouve la virgule dans le titre bizarre, mais soit)

 - https://beta.grafikart.fr/forum?page=4 `Forum | Grafikart` il manque le numéro de la page

_Je suis peut-être tatillon sur certains points_

**Comment by endermctv** [comment]
> *Je suis peut-être tatillon sur certains points*

je suis d'accord

**Comment by endermctv** [comment]
https://beta.grafikart.fr/error.html : réglé (https://github.com/Grafikart/Grafikart.fr/pull/225/files#diff-b22a5ae01ad51f1ba0dfeda18a9e84eb717e5098034f8d95472763d5babcc33d)

**Comment by Grafikart** [comment]
> https://beta.grafikart.fr/tutoriels/distance-levenshtein-1372 Tutoriel vidéo Algorithmique : Distance de Levenshtein | Grafikart Le titre du tutoriel n'est pas directement au début et un onglet a une petite largeur, je verrais plutôt un Distance de Levenshtein — Algorithmique — Tutoriel vidéo | Grafikart

C'est pour le référencement ;)

Pour le reste c'est bon.

> Je suis peut-être tatillon sur certains points

Non c'est une bonne chose les titres sont important !
