### ISSUE TITLE
Notification au clic de "regarder plus tard"

### ISSUE THREAD

**Issue by CorentinStevens** [Grafikart/Grafikart.fr#226]
Lorsqu'on clique sur "regarder plus tard" il affiche "Tutoriel retiré de votre watchlist".

**Comment by endermctv** [comment]
D’ailleurs ce bug est présent sur la version actuelle de grafikart.fr.

**Comment by Grafikart** [comment]
Cette fonction a été retirée sur la nouvelle version du coup cela ne sera pas présent pour la nouvelle version.
