### ISSUE TITLE
[BETA] Pagination, page en trop

### ISSUE THREAD

**Issue by Rom1-J** [Grafikart/Grafikart.fr#230]
## Description
Sur certaines recherches (/recherche, pas le forum, aucun prob sur le forum), la pagination sort un nombre trop grand de page (ex: recherche gra donne 31 pages mais a partir de la 26eme page on a "Aucun résultat")

## Demo

https://user-images.githubusercontent.com/25200594/104518607-3981f280-55f8-11eb-926b-e26b0c7376e6.mp4

**Comment by ComFoxx** [comment]
Aussi avec une recherche vide on a une pagination qui va jusqu'à 142, bizarre
