### ISSUE TITLE
[BETA] CSS Superposition d'éléments

### ISSUE THREAD

**Issue by Rom1-J** [Grafikart/Grafikart.fr#233]
## Description
Lorsqu'on suit plusieurs tuto (mise en pratique de la POO par exemple), dans la section "Vidéos en cours de visionnage" sur notre profil et la page d'accueil, lesdites vidéos se superposent

## Demo
![image](https://user-images.githubusercontent.com/25200594/104601303-5d861800-567a-11eb-95d0-d666a8e86f44.png)
![image](https://user-images.githubusercontent.com/25200594/104601455-8e664d00-567a-11eb-937f-123f28eb4fe0.png)

**Comment by Rom1-J** [comment]
Dans le meme theme :

Sur /forum, quand on en créer un avec beaucoup trop de tag, ca envahit les autres forums

## Demo
![image](https://user-images.githubusercontent.com/25200594/104603353-9c1cd200-567c-11eb-8748-3029b4f358b8.png)

**Comment by Hypario** [comment]
petite proposition, pour résoudre le problème de tag
il faudrait un genre de tag ... (que l'utilisateur ne peux pas mettre) qui s'affiche au bout d'un nombre élevé (admettons 3, 4 tags) 
qui lorsqu'il est survolé par le curseur, affiche tout les tags dans une boite, ce qui éviterais ce comportement)
