### ISSUE TITLE
[BETA] Adresse email de plus de 255 caractères

### ISSUE THREAD

**Issue by ComFoxx** [Grafikart/Grafikart.fr#236]
Lorsque l'on tente de s'inscrire avec une adresse email de plus de 255 caractères, on obtient une erreur serveur.

https://user-images.githubusercontent.com/17570186/104615172-44389800-5689-11eb-9a69-3e6a0f6b32ac.mp4

**Comment by endermctv** [comment]
du coup c'est un gros problème
