### ISSUE TITLE
[BETA] Validation de l'adresse email

### ISSUE THREAD

**Issue by ComFoxx** [Grafikart/Grafikart.fr#237]
Je m'inscris :
![image](https://user-images.githubusercontent.com/17570186/104618397-f160df80-568c-11eb-8cb6-b464c28bd09c.png)

Mais imaginons que je ne reçois pas l'email, ou trop tard ie. plus de deux heures après mon inscription (pour plein de raisons possibles) :
![image](https://user-images.githubusercontent.com/17570186/104618615-3a189880-568d-11eb-8d46-62e3115cc330.png)

Alors je ne pourrais plus m'inscrire car l'adresse email est déjà utilisée :
![image](https://user-images.githubusercontent.com/17570186/104618783-6fbd8180-568d-11eb-8321-9713d3a4cc90.png)

En plus j'ai un compte qui n'est pas validé auquel je ne peux pas me connecter…

**Comment by Grafikart** [comment]
Je ne préfère pas changer le comportement de ce système. Au pire les gens m'enverront un email.
