### ISSUE TITLE
[BETA] Problème de marge texte "Les derniers tutoriels" sur mobile

### ISSUE THREAD

**Issue by Daniel-Mendes** [Grafikart/Grafikart.fr#239]
Je ne sais pas si c'est voulu mais je ne pense pas.

![Screenshot_20210115-085030](https://user-images.githubusercontent.com/28825568/104697058-768cd880-570f-11eb-9ec4-0a2616786e9b.jpg)

Le titre touche la "card" du dessus.

Je suis sur mobile OnePlus 7, je n'ai pas reproduis le problème sur ordinateur avec la simulation des tailles d'écran, donc je ne sais pas si tu vas pouvoir le voir.

**Comment by ComFoxx** [comment]
Cela semble avoir été corrigé, néanmoins, je trouve un peu bizarre sur smartphone quand tout se met en une colonne d'avoir "Les dernières formations" écrit en haut du bloc mais "Les derniers tutoriels" et "Tous les lives" écrit en bas du bloc.
![image](https://user-images.githubusercontent.com/17570186/104814444-2d23b280-580f-11eb-8678-17ea7f61ced0.png)
