### ISSUE TITLE
[BETA] Problème affichage tags Forum

### ISSUE THREAD

**Issue by rudstone** [Grafikart/Grafikart.fr#241]
Lorsque nous sommes sur la page "/forum", c'est le bordel au niveau de l'affichage des tags par topic, quand il y en a trop...

![2021-01-15 19_38_35-Window](https://user-images.githubusercontent.com/70549774/104765661-86390b00-5769-11eb-8b66-2200ca7482d6.png)

**Comment by AlexandrePetrone** [comment]
Le problème a été résolu en limitant le nombre de tags que l'on peut ajouter.
