### ISSUE TITLE
[BETA] ?? (JS) XXXXXXXX qui se glissent dans les champs texts

### ISSUE THREAD

**Issue by Rom1-J** [Grafikart/Grafikart.fr#243]
## Description
Lorsqu'on envoie un message contenant un lien sur un forum, le lien ne sera pas effectif comme mentionné dans une issue précédente mais, en editant le message sans rien changer de sorte a rendre le lien actif, cliquer sur le lien et faire fleche arriere sur le nav, des XXXXXXXXXXXXX irons se glisser sur tous les champs text

## Demo

https://user-images.githubusercontent.com/25200594/104813794-b507bd80-580b-11eb-9258-19e9cfbcdcd3.mp4

## Étapes
- Aller sur un forum
- Envoyer un message contenant un lien (ex: ``[slt](/azeaze)``)
- Editer le message qui vient d'etre envoyer sans rien changer de sorte a rendre le lien clickable
- Cliquer sur le lien
- Faire fleche retour sur le navigateur pour aller sur la page précédente (donc le forum)
- See

Les champs texts, pour envoyer un message ou en editer un seront alors remplis d'une suite de X non supprimable ni selectionnables

**Comment by ComFoxx** [comment]
Le coupable : https://github.com/codemirror/CodeMirror/search?q=xxxxxxxxxx

**Comment by Grafikart** [comment]
J'ai mis à jour le problème des liens et je pense que le problème n'est plus reproduisible. Je te laisse me confirmer ça pour fermer le ticket

**Comment by Rom1-J** [comment]
Oki, je retente demain

**Comment by Rom1-J** [comment]
Le probleme est toujours présent comme le montre ces 2 videos


https://user-images.githubusercontent.com/25200594/104885841-fc579080-5968-11eb-9a20-9390e355f7be.mp4


https://user-images.githubusercontent.com/25200594/104885845-feb9ea80-5968-11eb-8f38-a6b31d4d2c27.mp4

**Comment by Grafikart** [comment]
Trop spécifique je considère ça comme un ultra edge case ^^
