### ISSUE TITLE
[BETA] Impossible d'ajouter une réponse à un topic

### ISSUE THREAD

**Issue by trodix** [Grafikart/Grafikart.fr#244]
Si on trigger le message d'erreur qui indique que la chaine de caractère est trop courte (en mettant moins de 10 caractères), le bouton "Répondre" se disable.

On rajoute des caractères pour en avoir plus de 10, mais le bouton "Répondre" reste disable.

![image](https://user-images.githubusercontent.com/34584317/104817385-40d81480-5821-11eb-8c1e-7e7eb84aadee.png)

**Comment by Grafikart** [comment]
C'est corrigé !
