### ISSUE TITLE
Bug d'affichage boutons "pages suivantes".

### ISSUE THREAD

**Issue by tagleweb** [Grafikart/Grafikart.fr#247]
Sur la version Mobile, lorsque l'on va dans tutoriel et que l'on descend jusqu'au dernier tutoriel, les premiers boutons de pages suivantes s'affiche correctement mais pas le suivant.
![20210117_151749](https://user-images.githubusercontent.com/59423570/104845717-2f514400-58d7-11eb-87ee-6fb876824a42.jpg)

**Comment by tagleweb** [comment]
Après quelques investigations, il s'avère que le bug semble se produire uniquement sur certaines résolutions d'écrans de téléphone.

**Comment by antton-dev** [comment]
j'ai déjà créé une issue sur ce problème
