### ISSUE TITLE
[BETA] Design pages tutoriels + formations

### ISSUE THREAD

**Issue by rudstone** [Grafikart/Grafikart.fr#250]
Je trouve que le design original de la page live rend mieux sur les pages tutoriels + formations.
Cela caractérise une meilleure identité visuelle pour le site.

![2021-01-17 23_14_34-Window](https://user-images.githubusercontent.com/70549774/104857603-f71f2500-5919-11eb-8cf8-2cc2d0ea393d.png)

**Comment by Grafikart** [comment]
Tu veux dire quoi par 

>  design original de la page live 

Tu fais référence à quelle page ?

**Comment by rudstone** [comment]
Avec le grand logo de grafikart en gris en haut à gauche.

J'ai joins une capture d'écran avec l'application du style de la page live ;)

**Comment by rudstone** [comment]
Pourquoi pas mettre le même design de la page des tutoriels pour la page Formations, Premium, Blog et Forum ?
Cela apportera une cohérence entre toutes les pages (au lieu d'avoir un style différent pour chaque page) ;)
