### ISSUE TITLE
[BETA] Vidéo qui ne se télécharge pas apres connexion (premium)

### ISSUE THREAD

**Issue by Rom1-J** [Grafikart/Grafikart.fr#252]
## Description
Lorsqu'on est sur le site en non connecté et qu'on décide de cliquer sur "télécharger la video" sur un tuto, on est redirigé sur la page de connexion, on se co (avec compte premium) et une fois co plutot que de télécharger la video, le site nous ouvre la video a son adresse en .mp4

## Demo

https://user-images.githubusercontent.com/25200594/104906163-a3492600-5983-11eb-913a-0d329b7d37b8.mp4

**Comment by Grafikart** [comment]
C'est le comportement normal de la redirection. Je pense que le cas sera marginal et demanderait trop de modifications
