### ISSUE TITLE
[BETA] Flash 404 tutoriels

### ISSUE THREAD

**Issue by ComFoxx** [Grafikart/Grafikart.fr#253]
Lorsqu'il n'y a aucun tutoriels correspondant aux filtres, une 404 est retournée, doit déstabiliser Turbolinks et le cache, et on a un flash avec la page sans le CSS.
Le cache semblent tout de même fonctionnel après que la 404 ait été chargé une première fois.

On pourrait modifier cette ligne https://github.com/Grafikart/Grafikart.fr/blob/6dcb1b0cd76c756125b0f1076e5799e36cb2d0f7/src/Http/Controller/Course/CourseController.php#L61 pour toujours retourner une 200, mais si cette condition est présente, j'imagine qu'il y a une raison... (SEO ?)

https://user-images.githubusercontent.com/17570186/104908147-531f9300-5986-11eb-90c4-896301b02b2a.mp4

**Comment by Rom1-J** [comment]
chrome 89, pas de probleme :thinking:

**Comment by ComFoxx** [comment]
Je me demande si c'est si grave comme problème

**Comment by Grafikart** [comment]
Pour le coup la 404 est bien la bonne en tête que je veux renvoyer. Mais je vais essayer de voir si je peux produire le bug. C'est étrange qu'il désengage le CSS complètement :D

**Comment by Rom1-J** [comment]
J'ai réussi a avoir le flash mais impossible de faire en sorte qu'il soit a volonté, je l'ai eu apres reboot et en allant direct sur le site donc surement un probleme de cache, cependant impossible de le redeclancher apres meme en nav privée...

**Comment by endermctv** [comment]
bah en vrai c'est un problème qui pourrait en poser d'autres, donc c'est problématique...

**Comment by Grafikart** [comment]
Vu que le cas arrive vraiment de manière très rare et n'est pas bloquant pour le fonctionnement je ferme cette issue.
