### ISSUE TITLE
[CSS]: La barre de  progression d'une  formation

### ISSUE THREAD

**Issue by Scott-Tresor** [Grafikart/Grafikart.fr#276]
Apres la fin d'une formation  la barre de progression dépasse la carde
![image](https://user-images.githubusercontent.com/34010260/105347132-24582580-5bef-11eb-9d3f-cefae1e1a333.png)

**Comment by Grafikart** [comment]
Tu pourrais me donner ton pseudo sur le site ? pour que je puisse voir ce qui se passe sur ton compte ?

**Comment by Scott-Tresor** [comment]
scott tresor

**Comment by Grafikart** [comment]
Ce bug était lié à https://github.com/Grafikart/Grafikart.fr/issues/277
Le calcul de la progression mélangé les données de tout le monde ^ ^
