### ISSUE TITLE
[BETA] Progression formation

### ISSUE THREAD

**Issue by Spooky063** [Grafikart/Grafikart.fr#277]
Quand on se situe sur une formation, la barre de progression indique n'importe quoi.

Cette formation a été visionné en entier
![Capture d’écran de 2021-01-21 16-24-09](https://user-images.githubusercontent.com/1242071/105372014-7ad05e80-5c05-11eb-88fb-060db007c4e9.png)

1 seule vidéo a été visionné
![Capture d’écran de 2021-01-21 16-24-21](https://user-images.githubusercontent.com/1242071/105372041-80c63f80-5c05-11eb-8c99-d5f76b205a04.png)

**Comment by Scott-Tresor** [comment]
chez moi la progression est normal
