### ISSUE TITLE
Bug d'affichage si l'on navigue rapidement sur le forum

### ISSUE THREAD

**Issue by TheTakylo** [Grafikart/Grafikart.fr#278]
En naviguant rapidement sur le forum, au bout de 3-4 pages la suivante devient une 404, alors que si on navigue doucement il n'y a pas d'erreurs.

Et quand on fait un retour en arrière: bug d'affichage sur le site, il faut refresh.

https://user-images.githubusercontent.com/10907922/105374964-8cffcc00-5c08-11eb-880c-9e2c3e5c0257.mp4

**Comment by Grafikart** [comment]
Ce problème était lié à la configuration peu du parefeu.
