### ISSUE TITLE
(JS) Incohérence dans la page premium

### ISSUE THREAD

**Issue by Kareylo** [Grafikart/Grafikart.fr#281]
### Description

Lorsqu'on utilise la checkbox pour passer d'un premium de 1 mois à 1 an, le texte en dessous ne change pas

### Demo
![XLm1JV6UHc](https://user-images.githubusercontent.com/4358740/105486045-28974800-5cae-11eb-9bf9-53d754ba861a.gif)

### Étapes

- Aller sur la page /premium
- Cliquer sur la checkbox
- Le texte du bouton ne change pas

**Comment by YaFou** [comment]
De plus, 1 ans ne prend pas de s

**Comment by Kareylo** [comment]
De plus, lorsque l'on est pas connecté, la partie "(1 mois)" n'est pas présente
![image](https://user-images.githubusercontent.com/4358740/105486908-93954e80-5caf-11eb-9074-c62514f42cb2.png)
