### ISSUE TITLE
Problème de décalage des éléments sous Mac

### ISSUE THREAD

**Issue by alassaneousmane** [Grafikart/Grafikart.fr#287]
Hello,

Je suis sous Mac Book Pro et quand j'essaye d'accéder au nouveau site, je vois un décalage comme si le CSS n'est pas complètement pris en charge.
![Screen Shot 2021-01-23 at 18 50 51](https://user-images.githubusercontent.com/20798417/105609808-0552c280-5dac-11eb-9feb-5acb5714b2d3.png)

**Comment by Grafikart** [comment]
C'est bizarre ça me parait super petit tu es sur quel navigateur ?

**Comment by alassaneousmane** [comment]
Je suis sous Chrome

**Comment by alassaneousmane** [comment]
T'as pas le souci avec ton Mac Book?

**Comment by Grafikart** [comment]
Non c'est ce qui m'étonne le site rentre sur les 1280pxx720px de mon macbook :(

**Comment by Grafikart** [comment]
Vu que cela être un cas isolé je ferme cette issue.
