### ISSUE TITLE
[Load-time] Ajouter l'attribut preload afin d'accélérer le chargement de la page

### ISSUE THREAD

**Issue by SirMishaa** [Grafikart/Grafikart.fr#288]
D'après une estimation de Lighthouse, ajouter un attribut permettrait d'améliorer les performances de chargement de la page d'une demie seconde. 

https://web.dev/uses-rel-preload/?utm_source=lighthouse&utm_medium=lr

**Comment by Grafikart** [comment]
Le preload a été ajouté pour les chunks JS.
