### ISSUE TITLE
[Infra] Ajouter le support de l'http / 3 et du protocole QUIC

### ISSUE THREAD

**Issue by SirMishaa** [Grafikart/Grafikart.fr#289]
L'HTTP / 3 est une nouvelle norme ainsi que la relève de la version actuelle du protocole HTTP.

Il apporte beaucoup de nouveautés intéressantes qui améliorent de façon significative les performances. 

Il est maintenant supporté par Nginx, il est donc intéressant de modifier un peu la configuration afin de le supporter.

[Informations sur l'HTTP/3](https://kinsta.com/fr/blog/http3/)
[Tester le support de QUIC sur mon navigateur](https://quic.nginx.org/)

**Comment by Grafikart** [comment]
Cela ne sert à rien : https://caniuse.com/http3
