### ISSUE TITLE
[SEO] Attribut meta description manquant

### ISSUE THREAD

**Issue by SirMishaa** [Grafikart/Grafikart.fr#290]
L'attribut ``description`` est actuellement manquant. 

Celui-ci est plutôt important, car il est beaucoup utilisé par les crawlers pour l'indexation. 

Un article (en anglais) qui en parle et qui permet d'optimiser cette dernière afin d'augmenter le référencement de manière naturelle : https://moz.com/learn/seo/meta-description

**Comment by Grafikart** [comment]
Je n'en avais pas avant et je ne pense pas en remettre aujourd'hui car je n'ai pas les contenu pour.
