### ISSUE TITLE
Problème d'affichage du code dans les tutoriels

### ISSUE THREAD

**Issue by Superkooka** [Grafikart/Grafikart.fr#291]
Dans la partie écrite des tutoriels comme celui sur [l'oauth avec symfony](https://grafikart.fr/tutoriels/symfony-oauth-authenticator-1362) on peut y constater des soucis avec les parties de codes

![image](https://user-images.githubusercontent.com/35631093/105611090-9a0cee80-5db3-11eb-9af4-68456828a04e.png)

**Comment by Grafikart** [comment]
C'est réparé c'est dans le contenu
