### ISSUE TITLE
Une recherche vide sur le forum renvoie 0 résultat

### ISSUE THREAD

**Issue by pierreminiggio** [Grafikart/Grafikart.fr#292]
Si on fait une recherche sans mot clé, je pense que ça devrait afficher la même chose que ne pas faire de recherche.

Résultat actuel :
![image](https://user-images.githubusercontent.com/35456349/105611199-1dc6db00-5db4-11eb-8b7c-5cc28947e418.png)

Résultat auquel je m'attendrais : 
![image](https://user-images.githubusercontent.com/35456349/105611224-464ed500-5db4-11eb-870a-5bc75f9e68b3.png)

**Comment by oussaka** [comment]
fix dans #294 

Une recherche "vide" affichera le même résultat que "index" (/forum).
