### ISSUE TITLE
DESIGN : Carte Tutoriel

### ISSUE THREAD

**Issue by Grafikart** [Grafikart/Grafikart.fr#3]

**Comment by betaWeb** [comment]
Salut @Grafikart,

Concernant les cartes tutoriels (et formations par extension), je trouve l'idée d'avoir un liseré reprenant la couleur de la techno plutôt bonne. Alors peut-être plutôt partir sur un triangle (avec opacité) en bordure haut gauche ? Ça serait moins 'violent'.

Pour ce qui est des tags de difficulté, l'idée est très bonne et leur design est simple et efficace (juste à trouver une solution / placement optimal, notamment pour les titres longs).
Je pensais cependant remplacer `Facile`, `Moyen` et `Difficile` par `Débutant`, `Intermédiaire` et `Expert`, qu'en dis-tu ?
Et en profiter pour permettre de filtrer les tutos / formations par difficultés ? :)
