### ISSUE TITLE
Redirection sur la page d'accueil  si non premium

### ISSUE THREAD

**Issue by bnoufel** [Grafikart/Grafikart.fr#305]
Hello,

Si on est pas premium et qu'on souhaite "télécharger" les sources et vidéos on se fait rediriger sur la page d'accueil au lieu de `/premium` comme avant, c'est voulu ?

**Comment by Grafikart** [comment]
Non ce n'est pas voulu mais je n'arrive pas à reproduire le problème.

**Comment by TheTakylo** [comment]
J'ai également le même problème, je suis redirigé sur la page d'accueil.

**Comment by Grafikart** [comment]
@TheTakylo tu saurais me donner la page du tutoriel où le problème apparait ?

**Comment by TheTakylo** [comment]
Sur tous les tutoriel, voici une petite vidéo, peut-être que ça peut aider.

https://user-images.githubusercontent.com/10907922/105872473-bfd80480-5ffa-11eb-908c-9ff133ea5f86.mp4

**Comment by bnoufel** [comment]
@TheTakylo Perso le problème s'est résolu tout seul 🤔 essaie en nav privé voir si c'est pas un cache local. Je réessayerais demain voir si c'est revenu

**Comment by TheTakylo** [comment]
Le problème est effectivement résolu en navigation privé. Je vais voir pour vider mes caches
