### ISSUE TITLE
Authentification via Google Acount

### ISSUE THREAD

**Issue by 4l3x4ndr3** [Grafikart/Grafikart.fr#310]
Lors d'une tentative de connexion avec un compte Google j'ai eu le retour suivant :
Invalid state parameter passed in callback URL
![IMG_0548](https://user-images.githubusercontent.com/2023884/105990407-b3a78200-60a2-11eb-93d6-87f741f92342.PNG)

**Comment by Grafikart** [comment]
Le compte google a qquchose de particulier ? Car je n'arrive pas à reproduire le pb :(

**Comment by 4l3x4ndr3** [comment]
Je vais faire des tests et je reviens vers toi.
Le compte google n'a normalement rien de particulier, je l'utilisais pour me connecter à ton site

**Comment by 4l3x4ndr3** [comment]
Après plusieurs tests je ferme l'issue.
Il s'avère que le problème était dû à un problème de connexion en 4G.

Désolé pour le dérangement.
