### ISSUE TITLE
PWA

### ISSUE THREAD

**Issue by RodrigueAk47** [Grafikart/Grafikart.fr#311]
Render le site grafikart.fr installable avec progressive web app

**Comment by YaFou** [comment]
Je ne vois pas trop l'avantage que cela peut apporter.

**Comment by Grafikart** [comment]
@RodrigueAk47 Je ne pense pas que faire une PWA avec mode offline soit pertinent par contre avoir un moyen d'installer un racourci peut être pertinent donc je vais voir si il faut déclarer certaines choses pour faire ça.
