### ISSUE TITLE
Problème de logo sur la page Apprendre l'HTML

### ISSUE THREAD

**Issue by bfalsata** [Grafikart/Grafikart.fr#314]
Quand on est sur la page https://grafikart.fr/cursus il y a un logo pour la partie html et un autre pour la partie css et quand on va sur la page https://grafikart.fr/formations/html c'est le logo utiliser sur la page css qui est affiché

**Comment by rudstone** [comment]
@Grafikart changer l'ordre des tags depuis le dashboard ?

**Comment by Grafikart** [comment]
C'est corrigé, un problème de classement effectivement.
