### ISSUE TITLE
Pas d'authentification détectée sur certaines 404

### ISSUE THREAD

**Issue by bnoufel** [Grafikart/Grafikart.fr#315]
Hello,

Il y a un petit soucis sur certaines 404.

Sur la plus part tout vas bien, mais certaines, le thème black n'est plus présent par défaut, et on est détecté comme non authentifier.

- https://grafikart.fr/forum/454545454545 => Tout va bien
- https://grafikart.fr/forum/-42 => plus de thème et plus "auth"

**Comment by TheTakylo** [comment]
Même bug également

**Comment by oussaka** [comment]
Dans le premier cas  (https://grafikart.fr/forum/454545454545) C'est une erreur 500 qui est survenue : 
```
SQLSTATE[22003]: Numeric value out of range: 7 ERROR: value "454545454545" is out of range for type integer 
```
il faut changer le type de colonne.

Dans le second cas (https://grafikart.fr/forum/-42), je pense que c'est normal que l'utilisateur apparait comme not authenticated

> Security & 404 Pages¶
> 
> Due to the order of how routing and security are loaded, security information will not be available on your 404 pages. This means that it will appear as if your user is logged out on the 404 page (it will work while testing, but not on production).
source : https://symfony.com/doc/current/controller/error_pages.html

**Comment by bnoufel** [comment]
@oussaka Pour le premier lien c'est un example :) je voulais pas m'embêter à taper autre chose

Mais si tu veux une 404 avec un thème black authentifié :) https://grafikart.fr/tutoriels/fewfew

Faut pas s'arrêter à ce qui est mis sur l'issue ça reste que des petits examples ;)

**Comment by rudstone** [comment]
J'avais signalé le problème auparavant et @Grafikart m'avais répondu comme quoi ce n'était pas possible de corriger le problème...

**Comment by Grafikart** [comment]
Oui en fait les erreurs qui résultent d'une erreurs serveur (par exemple le 45454545454545) sont capturé trop tôt par Symfony et je ne peux rien y faire pour le moment. Je prévois en revanche de capturer ces erreurs en amont en revanche pour éviter le problème avant qu'il ne se produise. Aussi je ferme cette issue pour le moment.
