### ISSUE TITLE
progression sur Grafikart 

### ISSUE THREAD

**Issue by masoudLI** [Grafikart/Grafikart.fr#316]
Bonjour Grafikart,

je pense qu'il y a  un problème niveau de la barre de progression des buttons sur le site. Qd on finis la vidéo d'un tuto, la bar de la progression de button se finis pas, ca veut dire ca strock-dashbord se complète pas. je sais pas si je m'explique bien ou non.

**Comment by Grafikart** [comment]
Tu as un exemple à donner ? Tu peux me faire une capture ou me donner une page où ça arrive ?

**Comment by masoudLI** [comment]
https://user-images.githubusercontent.com/31687860/106252124-2dac4800-6216-11eb-8e1f-d03496046065.PNG
https://user-images.githubusercontent.com/31687860/106252176-4288db80-6216-11eb-8a0a-49671b0a75a5.PNG
https://user-images.githubusercontent.com/31687860/106252362-7b28b500-6216-11eb-8f63-ad36d36f6cde.PNG

je sais pas si t'arrive a les voir !

**Comment by masoudLI** [comment]
en fait, après d'avoir réessayé, je pense que ca ns arrive que qd on est pas connecté !
