### ISSUE TITLE
Non Commercial LICENSE

### ISSUE THREAD

**Issue by bernard-ng** [Grafikart/Grafikart.fr#32]
je propose cette license :

[Attribution-NonCommercial-ShareAlike 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/)

# You are free to:
  *  Share — copy and redistribute the material in any medium or format
   * Adapt — remix, transform, and build upon the material 

# under the following terms : 
   *  Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

   *  NonCommercial — You may not use the material for commercial purposes.

   *  ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.

   * No additional restrictions — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.

**Comment by Grafikart** [comment]
Le souci de cette licence c'est que techniquement je n'autorise pas qqun a prendre le code source & design pour créer une nouvelle version du site.

**Comment by SwithFr** [comment]
Ce qui est plutôt une bonne chose dans un sens non ? Le but c'est juste de contribuer à sa réalisation, pas de pouvoir en faire des copies pour n'importe qui non ?

**Comment by bernard-ng** [comment]
@SwithFr exactement, @Grafikart je comprends mieux maintenant
