### ISSUE TITLE
Mode dark s'annule lorsqu'on se connecte

### ISSUE THREAD

**Issue by dy05** [Grafikart/Grafikart.fr#324]
Hello
J'ai active le mode sombre
Apres je me connecte, et je nai plus le mode sombre
Pareil que si j'active le mode sombre lorsque je suis connecte, et que je desactive
A la deconnexion, le mode sombre revient.

Je propose d'avoir le mode sombre dans les params de l'utilisateur a null des le depart.
Si c'est set a true a false avant qu'on ecrase les params du navigateur. Sinon on utilise ceux du Navigateur.
Et pourquoi pas pousser plus loin en mettant à jour les donnees du navigateur (cookie) lorsque l'utilisateur change de mode

**Comment by ValBocquet** [comment]
Je n'ai pas le même comportement moi. 
Si connecté en sombre et que je le mets en clair, puis déconnecte, je reste en clair. 
Ca garde juste en mémoire pour l'utilisateur, pour moi ça fonctionne bien.

**Comment by dy05** [comment]
> 
> 
> Je n'ai pas le même comportement moi.
> Si connecté en sombre et que je le mets en clair, puis déconnecte, je reste en clair.
> Ca garde juste en mémoire pour l'utilisateur, pour moi ça fonctionne bien.
je pense pas qu'on se soit compris
Mais j'imagine que c'est le comportement souhaite par @Grafikart 
Mon soucis etait que lorsque je change le mode etant connecte, ca ecrase celui preenregistre deja dans le navigateur avant la connexion, et aussi que si je suis deja en mode dark avant avant d'etre connecte, que ca puisse prendre cela en compte et afficher directement le mode dark.
Mais ca peut etre plus de travail moins prioritaire je suppose. je vais donc fermer cet issue.
