### ISSUE TITLE
Problèmes d'overflow et de responsive dans le forum

### ISSUE THREAD

**Issue by antton-dev** [Grafikart/Grafikart.fr#325]
Hey, 
J'ai trouvé trois problèmes dans le forum, sur la liste des sujets.
 - S'il y a trop de tag pour un sujet, une scrollbar apparait, mais elle n'est pas actionnable. 
![image](https://user-images.githubusercontent.com/64503329/106384901-aa355700-63cd-11eb-8368-8751afd2d31d.png)

- Si le navigateur est compris entre 1000px et 800px, un titre trop long ne va pas revenir à la ligne et va déborder sur les tags.
![image](https://user-images.githubusercontent.com/64503329/106385019-56773d80-63ce-11eb-9816-edb6147142ff.png)

- A 800px exactement, le design est explosé.
![image](https://user-images.githubusercontent.com/64503329/106385057-81619180-63ce-11eb-8bef-0e89d66fbee5.png)

testé sur Microsoft Edge, Google Chrome et Firefox

**Comment by Grafikart** [comment]
Bien trouvé, j'ai ré-affiné la présentation cela devrait être beaucoup mieux.
