### ISSUE TITLE
Connexion FB/Google/Github

### ISSUE THREAD

**Issue by Micka91** [Grafikart/Grafikart.fr#328]
Hello hello, juste pour signaler que la connexion via les réseaux ne fonctionne plus

Erreur 400 : redirect_uri_mismatch
The redirect URI in the request, https://grafikart.fr/index.php/oauth/check/google, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/${your_client_id}?project=${your_project_number}

**Comment by Grafikart** [comment]
Tu peux me donner la page d'origine car le redirect m'étonne beaucoup ici.

**Comment by Micka91** [comment]
Tout fonctionne actuellement, je sais pas si tu as touché à quelque chose de ton coté. 
L'erreur ce produisait sur la page suivante 

https://grafikart.fr/connexion?redirect=/

Si tu cliquais sur FB/Google/Github, tu avais l'erreur du dessus, mais tout est rentré dans l'ordre.
