### ISSUE TITLE
[Zoom windows 125%] Scrolling horizontal page tutoriel

### ISSUE THREAD

**Issue by stromcon** [Grafikart/Grafikart.fr#337]
Hello !

Sur mon laptop, il y a un scrolling horizontal sur la page tutoriel ce qui fait que certains elements ne sont pas visibles, de plus la scrollbar n'est elle même pas visible :

![image](https://user-images.githubusercontent.com/6690149/107072533-836c8b80-67e6-11eb-951d-8198c226905c.png)

OS : windows
Browser : Chrome dernière version
Niveau de zoom Chrome: 100%
Résolution : 1920 * 1080
Niveau de zoom windows : 125 % (**Je pense que c'est ce qui pose le soucis)**

EDIT : j'ai édité le titre, c'est bel et bien le niveau de zoom à 125% de windows qui provoque le soucis. Sur l'ancienne UI de Grafikart ce n'était pas présent et c'est vraiment nécessaire en terme d'accessibilité pour moi sinon je n'arrive pas bien à lire et je sais que nous sommes nombreux à avoir le zoom windows ou chrome à 125 % par défaut :

![image](https://user-images.githubusercontent.com/6690149/107073645-e7438400-67e7-11eb-8832-d23a17d3b13f.png)

**Comment by Grafikart** [comment]
Ok je crois que tu viens de mettre le point sur un autre bug
Cela devrait corriger #287

**Comment by Grafikart** [comment]
Tu peux me donner la valeur renvoyer par window.innerWidth ?

**Comment by stromcon** [comment]
![image](https://user-images.githubusercontent.com/6690149/107128763-b5eab700-68c0-11eb-8370-587074de3aa8.png)

window.innerWidth=1536, je précise que mon écran est bien du 1920*1080 (le zoom fait ça)

**Comment by stromcon** [comment]
@Grafikart je suis repassé sur le site récemment, cette issue semble corrigée

**Comment by Grafikart** [comment]
Ok je ferme du coup
