### ISSUE TITLE
CSS, switch theme sur ios

### ISSUE THREAD

**Issue by Rom1-J** [Grafikart/Grafikart.fr#339]
## Description
Sur iOS 14.5 (plus de batterie dans les autres tel à l'heure actuelle pour tester sur d'autres versions), le switch pour passer du thème sombre à clair marche sur toutes les pages SAUF /tutoriels

## Demo
https://user-images.githubusercontent.com/25200594/107100507-db21eb80-6814-11eb-83fd-eb472d56213c.mp4

## Étapes
- Utiliser safari sur iOS
- Se rendre sur / (constater que le switch marche)
- Se rendre sur /tutoriels (constater que le style ne marche pas et que la lune est en haut de page)

**Comment by Grafikart** [comment]
Si tu charge /tutoriels (en actualisant la page) là tu vois bien le switch correctement ?

**Comment by Rom1-J** [comment]
> Si tu charge /tutoriels (en actualisant la page) là tu vois bien le switch correctement ?

Une fois qu'on actualise /tutoriels, oui, le switch marche

**Comment by Rom1-J** [comment]
Plus reproduisible
