### ISSUE TITLE
Il y a  pas des contenu  sur la card

### ISSUE THREAD

**Issue by Scott-Tresor** [Grafikart/Grafikart.fr#341]
![image](https://user-images.githubusercontent.com/34010260/107146890-85a02880-6953-11eb-8f2c-b43ec3cc323a.png)
Apres une connexion, j'ai constater  qu'il y a pas des contenues  dans la carde  et  il y avait  un cursus que  j'avait  finit  et  je  n'arrive plus a  retrouver  cela  sur la list des  cursus  finit

**Comment by Grafikart** [comment]
C'est corrigé, ce sont des anciennes formations que j'ai mis offline mais la condition n'était pas bonne. J'ai corrigé le problème depuis l'administration.

**Comment by Scott-Tresor** [comment]
d'accord
