### ISSUE TITLE
Mettre à jour le libellé " Aucune réponse " et supprimer le bouton " Signaler le message " (quand on poste soit-même le message)

### ISSUE THREAD

**Issue by farpat** [Grafikart/Grafikart.fr#342]
Salut :)

![image](https://user-images.githubusercontent.com/24484284/107186845-4e7a5780-69e5-11eb-90f4-c1cd83afcd94.png)

- Bug " Aucune réponse "
Dans la capture, une réponse a été apportée mais on ne voit " Aucune réponse ". Il faut réactualiser la page pour que ce libellé soit mise à jour.

- Bug " Signaler le message "
Je pense qu'on peut supprimer le bouton " Signaler le message " pour l'utilisateur courant.

**Comment by adrientiburce** [comment]
Hello, essaie peut-être de détailler un peu plus le problème pour que ce soit facilement reproductible (sur quel page, sur quel environnement ..)

Après un test sur le forum en production le **Bug** " Aucune réponse " peut-être généralisé : 
-  après ajout d'une réponse le nouveau nombre de réponses n'est pas pris en compte (il faudrait donc incrémenter le nombre de réponses, ou remplacer "Aucune réponse" par "1 réponse".
