### ISSUE TITLE
Connexion : Sensibilité à la casse au niveau de l'adresse email

### ISSUE THREAD

**Issue by oza75** [Grafikart/Grafikart.fr#345]
Lors de la connexion il y'a une sensibilité à la casse pour le champ adresse email.
Par example: 
Si je me suis inscrit avec oza@grafikart.fr et que j'essaie de me connecter avec Oza@grafikart.fr j'ai une erreur "Identifiant invalide."

**Comment by endermctv** [comment]
C'est normal, à la connexion il te demande **un nom d'utilisateur** et **pas une adresse email**. D'ailleurs il n'y a pas de champ "adresse email", c'est seulement à la connexion.

**Comment by Grafikart** [comment]
Cela a été corrigé.
