### ISSUE TITLE
Créer une page pour lister les révision en cours sur le profil

### ISSUE THREAD

**Issue by Grafikart** [Grafikart/Grafikart.fr#346]

**Comment by endermctv** [comment]
En vrai super bonne idée ! Pour moi ce serait nickel, étant donné que je contribue beaucoup aux articles du blog et aux contenus des tutoriels.

**Comment by adrientiburce** [comment]
J'ai testé le système de révisions en local et j'ai remarqué que la révision est supprimée de la table une fois acceptée. 
Est-ce que ce ne serait pas une meilleure idée d'en garder une trace pour que chaque utilisateur puis voir combien de révision ont été acceptés / refusées.

On pourrait ainsi ajouter d'autre fonctionnalités à partir de ca : 
- ajouter un badge "10 révisions acceptés"
- ajouter les "contributeurs" sur les articles à partir des users qui ont apportés des révisions acceptes.
- plus facilement gérer les spams en trackant les révision refusés pour un utilisateur.

**Comment by Grafikart** [comment]
J'y ai pensé quand l'idée du badge a été apporté. Je ne suis pas forcément fan du fait de garder des données pour rien (surtout que les articles peuvent être long) mais je pense plutôt partir sur un compte à incrémenter côté utilisateur. 

A voir ce qui serait le plus adapté.

**Comment by adrientiburce** [comment]
Dans ce cas tu pourrais aussi juste supprimer le champ content lorsque la révision a été acceptée. 
Mais je trove ca dommage de tout supprimer,  l'utilisateur pourrait aussi avoir accès aux liens des articles auxquels il a participé dans cette page par exemple.
