### ISSUE TITLE
Progression absente sur le player youtube pour les vidéos sans formation.

### ISSUE THREAD

**Issue by adrientiburce** [Grafikart/Grafikart.fr#347]
Pour les vidéos sans formation par ex [celle-ci](https://grafikart.fr/tutoriels/distance-levenshtein-1372) la progression est absente lorsqu'on lance la vidéo youtube alors qu'elle est bien enregistrée (et visible dans "Mon Profil").

Le problème n'est pas présent pour les vidéos avec formation.

**Comment by Grafikart** [comment]
Tu veux dire quoi par progression absente ?

**Comment by adrientiburce** [comment]
La vidéo Youtube ne redémarre pas la où on l'a quitté.
Le problème venait de le  la fonction showHistory qui n'était pas appelé pour les cours sans formation.
J'ai corrigé le problème [ici](https://github.com/Grafikart/Grafikart.fr/issues/347)

**Comment by Grafikart** [comment]
Super je teste ça cette apprem et je merge
