### ISSUE TITLE
Recherche et filtres (prioriser les videos les plus recentes dans les resultats)

### ISSUE THREAD

**Issue by ksom** [Grafikart/Grafikart.fr#36]
Bonjour @Grafikart 

Je ne sais pas si c'est déjà le cas mais je suggère l'utilisation d'Elasticsearch pour le search & filters.

Il me semble que dans une de tes videos tu expliquais avoir du mal a faire ressortir les formations qui sont les plus récentes.
L’idée serait de booster le score des résultats en fonction de leur date de creation. Voici un topic stackoverflow qui parle du sujet:
https://discuss.elastic.co/t/how-to-prioritize-more-recent-content/134100/2

**Comment by Grafikart** [comment]
Le choix a été mis sur typesense. La notion de fraicheur n'entre pour le moment pas dans le calcul mais on verra si cela est problématique. La recherche est déjà bcp plus pertinente que celle de la version actuelle.
