### ISSUE TITLE
Bouton « Marquer comme vue » - Tutoriel

### ISSUE THREAD

**Issue by ThomAs-25** [Grafikart/Grafikart.fr#362]
Bonjour,

L’idée serait d’ajouter un bouton « marquer comme vue » sous les vidéos tutoriels pour le suivi dans l’historique et l’effet visuel dans la liste des tutoriels disponible. En effet je regarde souvent sur l’application YouTube (grace aux notifications) et du coup j’ai pas mon suivi d’avancement quand je reviens sur le site. 

Bon courage, Thomas

**Comment by endermctv** [comment]
Pour marquer comme vu un tutoriel, tu peux aller à la fin de la vidéo d'un tutoriel (sur le site), c'est automatiquement marqué comme vu.

**Comment by Grafikart** [comment]
@endermctv ce n'est pas une solution car ce n'est pas pratique du tout.

**Comment by endermctv** [comment]
Je saus mais c'est une solution que j'ai trouvée

**Comment by barbuslex** [comment]
+1 need !

**Comment by Grafikart** [comment]
@barbuslex  @ThomAs-25  c'est en place (le bouton est en bas à droite dans la sidebar sous l'auteur)
