### ISSUE TITLE
Accès à l'API Plateform sur le site de Prod

### ISSUE THREAD

**Issue by rudstone** [Grafikart/Grafikart.fr#364]
Nous avons accès à l'API Plateform sur le site de Prod, et ainsi lister toutes les API existantes 
![2021-02-21 12_57_12-Window](https://user-images.githubusercontent.com/70549774/108624317-7f767580-7444-11eb-8a9a-7ec560bfe0b4.png)

**Comment by oussaka** [comment]
Les services sont listées
https://grafikart.fr/api/docs.json?spec_version=3
Mais ne sont pas utilisables.

En même temps, Si les services sont bien sécurisés, alors pourquoi les cacher!

**Comment by Grafikart** [comment]
C'est merge (ça ne sera pas visible en prod avant la prochaine MAJ)
