### ISSUE TITLE
Désabonnement d'un sujet du forum

### ISSUE THREAD

**Issue by Carouge10** [Grafikart/Grafikart.fr#368]
Bonsoir,
On ne peux "plus" se désabonner d'un sujet afin de ne plus recevoir de notification

**Comment by Grafikart** [comment]
Tu veux te désabonner des notifications emails ou aussi des notifications sur le site.

**Comment by Carouge10** [comment]
ceux par email sont "paramétrable" en générale
Avant quand tu souhaitais ne plus être notifier d'un sujet du forum au quelle tu as répondu, tu utilisais un bouton pour "ne plus recevoir de notification"

**Comment by Grafikart** [comment]
C'est en ligne, n'hésite pas à me dire si cela correspond à ce que tu voulais.

**Comment by Carouge10** [comment]
c'est bien cela. merci
Je vais faire le point sur le forum car il y a de petite chose à améliorer (notamment au niveau des sujets résolus dans la liste des sujets)
