### ISSUE TITLE
Technologies sans aucun tutoriels ni icône (et autres)

### ISSUE THREAD

**Issue by JustYuuto** [Grafikart/Grafikart.fr#372]
Bonjour,

En me *baladant* sur le site, j'ai pu remarquer que certaines technologies n'ont pas de tutoriels ni d’icône. Voici certaines que j'ai remarquées :
- [ungit](https://grafikart.fr/tutoriels/ungit) (aucun tutoriel ni d'icône)
- [Debian](https://grafikart.fr/tutoriels/debian) (aucun tutoriel)
- [MySQL Workbench](https://grafikart.fr/tutoriels/mysql-workbench) (aucun tutoriel)
- [MariaDB](https://grafikart.fr/tutoriels/mariadb) (aucun tutoriel)
- [XDebug](https://grafikart.fr/tutoriels/xdebug) (pas d'icône)
- [Titanium](https://grafikart.fr/tutoriels/titanium) (pas d'icône)
- [Babel](https://grafikart.fr/tutoriels/babel) (aucun tutoriel)
- [PHPStorm](https://grafikart.fr/tutoriels/phpstorm) (une formation mais pas de tutoriels)
- [Twig](https://grafikart.fr/tutoriels/twig) (pas d'icône)
- [WordPlate](https://grafikart.fr/tutoriels/wordplate) (pas d'icône)
- [SVG](https://grafikart.fr/tutoriels/svg) (pas d'icône)
- [Three.js](https://grafikart.fr/tutoriels/threejs) (aucun tutoriel ni d'icône)

La même mais pour les formations :
- [CakePHP 2](https://grafikart.fr/formations/cakephp) (pas d'icône)

J'ai aussi remarqué certains tutoriels sans technologies :
- [La programmation fonctionnelle](https://grafikart.fr/tutoriels/programmation-fonctionnelle-878)

Au passage d'autres tutoriels auquels il manque des technologies :
- [Carte interactive en SVG](https://grafikart.fr/tutoriels/carte-interactive-791) (il manque [SVG](https://grafikart.fr/tutoriels/svg))
- [Jest](https://grafikart.fr/tutoriels/jest-test-framework-1202) (il manque [Jest](https://grafikart.fr/tutoriels/jest))
- [Particules 3D avec Three.js](https://grafikart.fr/tutoriels/three-js-3d-289) (il manque [Three.js](https://grafikart.fr/tutoriels/threejs))

Voilà, j'espère que ça aidera @Grafikart et la communauté !

**Comment by endermctv** [comment]
Du coup après 2 mois d'inactivité sans aucun changement (j'ai tout vérifié), ça donne quoi @Grafikart ? (désolé pour la mention)
