### ISSUE TITLE
Typescript ou JavaScript ?

### ISSUE THREAD

**Issue by Grafikart** [Grafikart/Grafikart.fr#38]
J'ai commencé à travailler un peu sur la partie front et je m'interroge sur le choix du langage

## Pourquoi Typescript ?

Permet de mieux organiser le code et d'avoir une vérification statique du code. Le problème est qu'en contrepartie je trouve que le code peut devenir moins lisible avec des cas où le type doit être forcé.

https://github.com/Grafikart/Grafikart.fr/blob/master/assets/js/elements/RecapLiveElement.ts

Aussi, le typescript semble sur certains point s'écarter du JavaScript classique (private / public, décorateur...) et il y a un risque de breaking change qui oblige plus tard à repenser le code :( .

## Pourquoi pas ?

Si on retire typescript on retire aussi un outil nécessaire à la compilation du code. On peut aussi imaginer que dans un avenir le support des modules et des outils comme https://www.snowpack.dev/ permettront de ne plus avoir aucune étape de compilation. 

Il faudra alors utiliser des commentaires (jsdoc) pour spécifier le typage. Mais je ne suis pas sûr qu'il existe un outil capable d'analyser le code par ce biais là.

**Comment by Arteneko** [comment]
Typescript +1

**Comment by felixdorn** [comment]
Typescript +1

**Comment by SwithFr** [comment]
Personnellement je vote JavaScript. Je suis pas certain que le TS apporte vraiment beaucoup pour ce genre de projet. Le rapport prise de tête/avantage est trop élevé à mon gout

**Comment by KevinTss** [comment]
De mon coté je ne conseille pas TypeScript, je ne l'ai pas beaucoup utilisé mais de ce que je constate il a été créer pour pouvoir amener des patterns back-end sur du front. 
Pas sur que ce soit adapté, de plus, le code se complexifie pas mal et deviens moins lisible comme tu l'as dit.

Je suis prenant de coder just en JS avec des bons principe de DRY et Separation Of Concern. Si le code est bien écrit le typescript n'est pas nécéssaire selon moi.

Il y a aussi quelque bug encore j'ai pus voir du coup tu seras dépendant de Microsoft pour les fix.

**Comment by betaWeb** [comment]
Je rejoins l'avis de @SwithFr et @KevinTss, en cela que TypeScript n'est pas vraiment pertinent pour du code purement frontend et pour ce genre de site. 
Rester en JS pur (ou passer par un framework, peu importe) paraît plus envisageable, cela permettra de rendre le code moins complexe et surtout moins dépendant.

**Comment by bcdbuddy** [comment]
Je reste d'avis sur du typescript étant donné que cela permet de capturer certaines erreurs en amont

**Comment by Grafikart** [comment]
Je viens de faire une version sans Typescript de mon custom element.

Pour le moment je pense continuer sans typescript car le tooling est trop contraignant par rapport à mes besoins (je ne compte créer que quelques custom elements). On utilisera JSDoc pour assurer les bons types et une bonne compréhension du code (j'ai aussi désactivé babel car je veux limiter les transformation du code tant que possible). 

Si à un moment donné le code devient trop fouillis on re-basculera sur TypeScript.

**Comment by bcdbuddy** [comment]
compréhensible. d'accord! la JSDoc aussi ça marche
