### ISSUE TITLE
Connexion et Inscription en 404

### ISSUE THREAD

**Issue by MysterKB** [Grafikart/Grafikart.fr#387]
Hello,

J'avais pas d'idée de titre, mais lorsqu'on est connecté et qu'on tombe sur une page 404, là où habituellement y'a notre pseudo etc, c'est remplacé par le mode non connecté, enfin comme si on étais pas connecté donc y'a connexion et inscription

Je sais pas si c'est normal du coup :]

**Comment by oussaka** [comment]
Duplicate of #315
