### ISSUE TITLE
Style de l'icône info n'est pas correct

### ISSUE THREAD

**Issue by HoussemTN** [Grafikart/Grafikart.fr#388]
Bonsoir,
Je ne sais pas si c'est le résultat attendu d'avoir une icône de cette taille ou non. En tout cas je partage : 
![image](https://user-images.githubusercontent.com/33376041/112698752-ab917600-8e8a-11eb-8071-252b6c91fa74.png)
Lien vers ce Tutorial : https://grafikart.fr/tutoriels/module-commentaires-api-platform-1310

**Comment by Grafikart** [comment]
Bien vu !
