### ISSUE TITLE
Logo d'Infomaniak en Dark Mode

### ISSUE THREAD

**Issue by JyVers** [Grafikart/Grafikart.fr#390]
C'est très bête mais le logo de l'hébergeur, "infomaniak" trouvable dans le footer n'est pas en png, donc il a un fond blanc même quand le site est en dark mode !

**Comment by Grafikart** [comment]
Infomaniak n'a pas de logo pour du dark mode sur la page presse du coup je n'ai pas forcément d'assets pour gérer ce cas :(
