### ISSUE TITLE
Bouton "Marquer comme lu" visible et cliquable sur un tutoriel non disponible

### ISSUE THREAD

**Issue by NetherMCtv** [Grafikart/Grafikart.fr#398]
Le bouton "Marquer comme lu" est visible et cliquable (l'action s'effectue bien) sur un tutoriel non disponible :

![image](https://user-images.githubusercontent.com/55290516/122044685-12189700-cddd-11eb-9efb-696bc321075e.png)

**Comment by Grafikart** [comment]
Ce n'est pas grave je pense car tu peux considérer que tu l'a vu en lisant le contenu parfois

**Comment by NetherMCtv** [comment]
Ok merci !
