### ISSUE TITLE
DESIGN : Homepage

### ISSUE THREAD

**Issue by Grafikart** [Grafikart/Grafikart.fr#4]

**Comment by betaWeb** [comment]
Salut @Grafikart,

Je ne savais pas trop où mettre cette remarque concernant la nouvelle charte que tu as choisi pour ce projet de refonte; juste partager mon avis : les couleurs que tu as choisi sont parfaites, ce vert (un vert sapin ?) est vraiment sobre, ça respecte la charte actuelle tout en y apportant un peu de 'modernité' :)
Pour moi il n'y a rien à dire de ce côté là.

**Comment by felixdorn** [comment]
J'ai une suggestion pour aérer un peu le design de la page d'acceuil

Les bordures sont rarement la solution, j'ai donc une propositions pour la section `Formations mises à jour récemment`, on enlève le séparateur du footer et on mets un background un peu plus contrasté, perso sur l'exemple, je suis passé de `#F9F9F9` à `#F1EFEF`

> Le design actuel

![MAJFormationsOld](https://user-images.githubusercontent.com/55788595/67969680-0aa57980-fc0a-11e9-884e-eee5e1d7ec40.PNG)

> Modifié selon ce que j'ai dit ci-dessus

![MAJFormations](https://user-images.githubusercontent.com/55788595/67969679-0aa57980-fc0a-11e9-9216-b35fd78faa9b.PNG)

**Comment by betaWeb** [comment]
> J'ai une suggestion pour aérer un peu le design de la page d'acceuil
> 
> Les bordures sont rarement la solution, j'ai donc une propositions pour la section `Formations mises à jour récemment`, on enlève le séparateur du footer et on mets un background un peu plus contrasté, perso sur l'exemple, je suis passé de `#F9F9F9` à `#F1EFEF`
> 
> > Le design actuel
> 
> ![MAJFormationsOld](https://user-images.githubusercontent.com/55788595/67969680-0aa57980-fc0a-11e9-884e-eee5e1d7ec40.PNG)
> 
> > Modifié selon ce que j'ai dit ci-dessus
> 
> ![MAJFormations](https://user-images.githubusercontent.com/55788595/67969679-0aa57980-fc0a-11e9-9216-b35fd78faa9b.PNG)

@felixdorn le design que tu proposes est vraiment sympa, ce n'est pas grand chose et pourtant je trouve que ça change tout : ça allège considérablement les cartes :)

**Comment by Grafikart** [comment]
J'avoue c'est beaucoup mieux

**Comment by felixdorn** [comment]
Toujours vivant, toujours debout :p

J'ai regardé les cursus et vu que je cite `Cette idée c'est caca` xD. J'ai essayé de redesigner ça rapidos.

Je suis reparti de zéro, donc il n'y a pas vraiment d'étapes pour passer de l'un à l'autre.

> La version caca
![image](https://user-images.githubusercontent.com/55788595/67994281-b8ce1500-fc44-11e9-87fd-f6e775492b0f.png)

> Re-designée
![image](https://user-images.githubusercontent.com/55788595/67994446-95579a00-fc45-11e9-849b-4e4cc84f34ca.png)
