### ISSUE TITLE
Bugs et améliorations sur les podcasts

### ISSUE THREAD

**Issue by YaFou** [Grafikart/Grafikart.fr#400]
- [x] Sur [cette page](https://grafikart.fr/podcasts/2), la vidéo apparait deux fois, je ne sais pas si c'est attendu. De plus, les autres podcasts ont une seule vidéo associée.
---
- [x] Sur la page d'accueil, il y a quatre podcasts qui sont affichés : 
![image](https://user-images.githubusercontent.com/33806646/123269395-3c660500-d4ff-11eb-9744-a1464ed6e70e.png)
Or lorsque l'on clique sur l'un des trois premiers, dans la liste des autres podcasts, seuls trois sont affichées : 
![image](https://user-images.githubusercontent.com/33806646/123269576-661f2c00-d4ff-11eb-8537-9f94ddf2da4d.png)
De plus, lorsque l'on clique sur le podcast le plus récent, nous avons bien les quatre podcast dans la liste : 
![image](https://user-images.githubusercontent.com/33806646/123269706-8353fa80-d4ff-11eb-86ad-7b8c6ea6dc81.png)
---
- [x] Sur téléphone, la liste ne se redimensionne pas et laisse un grand espace vide : 
![image](https://user-images.githubusercontent.com/33806646/123269918-b7c7b680-d4ff-11eb-954d-7855e6c56bc2.png)

**Comment by Grafikart** [comment]
Merci tout est corrigé ;)
