### ISSUE TITLE
Problème responsive page Podscast

### ISSUE THREAD

**Issue by abourtnik** [Grafikart/Grafikart.fr#403]
![WhatsApp Image 2021-06-29 at 14 42 27](https://user-images.githubusercontent.com/23094492/123799348-6eed7480-d8e8-11eb-9c76-1415d0c6aad9.jpeg)

**Comment by Grafikart** [comment]
C'est corrigé ! merci pour le report

**Comment by abourtnik** [comment]
Le problème semble persister. Refresh avec le cache.

<img width="1792" alt="Capture d’écran 2021-07-18 à 18 11 29" src="https://user-images.githubusercontent.com/23094492/126074404-d52f517c-42a8-435d-9357-a868dde608bf.png">
