### ISSUE TITLE
Page tutoriels : impossible de recliquer sur "tous" après un filtre sur le niveau

### ISSUE THREAD

**Issue by phiphou** [Grafikart/Grafikart.fr#405]
Dans la page tutoriels, après avoir filtré sur un niveau, on ne peut pas recliquer sur le niveau "tous" à la souris pour annuler le filtre. Si on navigue dans la liste au clavier on peut quand même sélectionner "tous". Le problème n’apparaît pas pour le filtre "technologies".

**Comment by Grafikart** [comment]
C'est corrigé ! merci pour le report
