### ISSUE TITLE
Alignement logo navbar

### ISSUE THREAD

**Issue by Rom1-J** [Grafikart/Grafikart.fr#410]
## Description
Sur Safari 15 d'iOS (pas eu l'occasion de tester sur d'autres plateformes), le logo à gauche dans la navbar n'est pas correctement aligné verticalement.

## Étapes
- Se rendre sur le site
- Constater

## Demo
![5954CF88-E82E-4AF9-9EBF-EF47EE8593DE](https://user-images.githubusercontent.com/25200594/128367581-81592a72-db25-42d1-b6dd-2187aa4c3316.png)

**Comment by moDevsome** [comment]
Défaut constaté également sur Firefox Mobile version 90.1.1

**Comment by moDevsome** [comment]
En réalité cela ne vient même pas du support, c'est purement CSS. Le problème est également présent si l'on redimensionne la fenêtre sur un écran de bureau.

Le problème vient du fait que la <li> parente à une valeur de "display" à "block" au lieu de "flex".

![image](https://user-images.githubusercontent.com/6329208/130326432-b82bee5c-8f33-47fc-8d95-8d4e2824cf24.png)

**Comment by paulclique** [comment]
Les propriétés css dans .header .header-nav .header__home @media 985px ne semblent pas utiles. C'est le display block qui est en trop. J'ai réalisé une pr
<img width="1136" alt="Capture d’écran 2022-02-13 à 16 14 30" src="https://user-images.githubusercontent.com/29452899/153759875-79baff7e-980e-4ed1-895c-78de52658bcc.png">
.
