### ISSUE TITLE
Pourquoi mettre toute la logique dans src/domain

### ISSUE THREAD

**Issue by cmukanisa** [Grafikart/Grafikart.fr#42]
Pourquoi mettre toute la logique dans src/domain voir meme les entités ?
A quoi servira le dossier natif Entity (même celui des  repository) ?

Merci

**Comment by Grafikart** [comment]
Le dossier Entity / Repository natif ne servira a rien (et n'existera pas). L'idée du dossier Domain (et Infrastructure) et de séparer la logique suivant le contexte de l'application. Pour avoir un groupement par concept rôle que par fonction.

**Comment by cmukanisa** [comment]
Merci beaucoup 
Maintenant en faisant ce refont, lors des mise à jour coté symfony, cette dernière n'aura pas des cases à faire .?  

Es-ce aussi une bonne pratique ?

**Comment by cmukanisa** [comment]
Faudra t-il utliser docker pour contribuer ?
Parce que `bin/console doctrine:database:create` ne fonctionne pas
D'après cette image

![Screenshot from 2020-02-16 08-16-54](https://user-images.githubusercontent.com/26385000/74605298-e07ea700-5094-11ea-8f70-d22d385166a5.png)

**Comment by Grafikart** [comment]
Idéalement oui docker te permet de simplifier le travail. Sinon tu peux arriver à le faire fonctionner sans mais il te faut pgsql & PHP 7.4

**Comment by nbordes-treezor** [comment]
> Merci beaucoup
> Maintenant en faisant ce refont, lors des mise à jour coté symfony, cette dernière n'aura pas des cases à faire .?
> 
> Es-ce aussi une bonne pratique ?

Lors d'une mise à jour Symfony il n'y aura aucun problème, depuis symfony 3.4 et la suppression de la notion de Bundle, tu peux organiser ton code comme tu le souhaite. Les évolutions de symfony se font au niveau de leur composant et des contrats d'interface et la encore symfony utilise le Semver pour éviter des Breaking change trop violent. 

En terme de "bonnes pratiques" Symfony émet des best practices que tu trouveras ici https://symfony.com/doc/current/best_practices.html. 
La structure mis en place par Grafikart peut s'apparenter à du DDD (mais de loin :D), séparation de la logique métier de son implémentation.
Mais pour le coup, chacun est libre de faire comme il veut. 
L'autowiring de Symfony fait qu'il reconnait automatiquement les controllers, les formulaires, les événements etc. peu importe la structure de tes dossiers.
