### ISSUE TITLE
Running the project in local

### ISSUE THREAD

**Issue by delhombre** [Grafikart/Grafikart.fr#420]
I have some difficulties to run the project. The make seed command doesn't work. It return something like USERID and GROUPID don't exist. Someone to help me please ?

**Comment by Fredkiss3** [comment]
Are you on linux ? 

Because these commands do not work on windows machines

**Comment by Grafikart** [comment]
Could you provide us with more information about your setup ?

**Comment by delhombre** [comment]
Hi, I'm on windows machine but i'm using wsl for this project
![Capture d’écran (34)](https://user-images.githubusercontent.com/52165447/143240848-624932de-749a-4fa3-833f-8627620551ba.png)
![Capture d’écran (35)](https://user-images.githubusercontent.com/52165447/143240853-7e56a5fe-89fd-4ce8-a26f-21dbd50341e2.png)

**Comment by delhombre** [comment]
Hi guys I finally found the solution. It was a Line Feed issue.
Reference to [https://stackoverflow.com/questions/50789087/windows-10-docker-usr-bin-env-php-r-no-such-file-or-directory](url)
