### ISSUE TITLE
Erreur upload avatar

### ISSUE THREAD

**Issue by christophe-44-27** [Grafikart/Grafikart.fr#426]
Hello @Grafikart,

Juste pour signaler un petit bug suite à l'upload d'un avatar. L'upload semble bien se faire mais à l'issu de l'upload on a un écran qui signale une erreur.

![image](https://user-images.githubusercontent.com/7846034/148859770-f4927fa1-36e7-4ccd-9fc2-bde0094079b4.png)

Merci :)

**Comment by Grafikart** [comment]
Peux tu vérifier si le problème est corrigé de ton côté ?

**Comment by christophe-44-27** [comment]
@Grafikart alors je n'ai plus d'erreur, mais l'avatar ne se change pas malgré un rafraîchissement de la page et un message de succès qui dit "Avatar mis à jour avec succès"
