### ISSUE TITLE
Login > Se souvenir de moi

### ISSUE THREAD

**Issue by Balsakup** [Grafikart/Grafikart.fr#428]
L'option `se souvenir de moi` ne fonctionne plus, à chaque fermeture du navigateur, la session est perdue

**Comment by Grafikart** [comment]
J'ai publié un fix sur ce problème hier soir, tu peux me dire si ça a corrigé le problème ?

**Comment by Balsakup** [comment]
@Grafikart, 

Tout à l'air fonctionnel. Je n'ai pas été déconnecté après fermeture de mon navigateur :+1:
