### ISSUE TITLE
Question concernant les Migrations

### ISSUE THREAD

**Issue by skPink** [Grafikart/Grafikart.fr#436]
Bonjour,

Je vois qu'aucun dossier 'Migration' du Framework Symfony n'est disponible dans le projet ? Comment gérer les migrations dans un projet en Prod 

      - Il faut laisser l'ensemble des migrations ?
      - Le dossier Migrations doit rester en local pour le dev, donc sur le serveur de production aussi ? 

Quelqu'un pourrait m'expliquer la bonne gestion des migration en production ?

**Comment by Grafikart** [comment]
Pour les questions de ce style je t'invite à plutôt rejoindre le discord.

Les migrations sont bien dans le projet mais dans un dossier spécifique : https://github.com/Grafikart/Grafikart.fr/tree/master/src/Infrastructure/Migrations
