### ISSUE TITLE
Intégration YouTube iFrame et RGPD

### ISSUE THREAD

**Issue by Brouilles** [Grafikart/Grafikart.fr#442]
Je pense, mais je ne suis pas expert avec le RGPD, qu'il y a un problème de conformité sur la page des tutoriels. 

Effectivement l'iframe n'est pas chargé avant un clic de l'utilisateur, mais il n'y a pas non plus de fenêtre de consentement. À noter que le no-cookie de Google ne respecte pas le RGPD.

Je cite :
> Wait: we have a solution: the youtube no cookie URL. Replace the URL of your youtube video youtube.com with youtube-nocookie.com, and you have a no cookie solution. You think. But you’re mistaken: the no cookie name for this URL is misleading, at least. Yes: the nocookie URL does not place cookies…. until you hit the play button. Then the user gets cookies, still without consent. That’s why Google refers to this method as the “delayed cookie option“.

De https://complianz.io/youtube-and-the-gdpr-how-to-embed-youtube-on-your-site/

**Comment by Grafikart** [comment]
Ah merci je ne savais pas du tout.

**Comment by Grafikart** [comment]
Re, je viens de lire la page mentionnant les confidentialité avancé et je ne retrouve pas le même wording que l'article.

> les contenus regardés dans le lecteur intégré lorsque le mode de confidentialité avancé est activé ne sont pas utilisés pour personnaliser l'expérience de navigation sur YouTube, que ce soit dans le lecteur intégré ou lors de toute utilisation ultérieure de YouTube.
> Lorsque des annonces sont diffusées sur une vidéo visionnée dans le lecteur intégré avec le mode de confidentialité avancé activé, elles ne sont pas personnalisées. Elles ne sont pas non plus utilisées pour personnaliser les annonces diffusées auprès des spectateurs en dehors de votre site ou de votre application.

**Comment by Brouilles** [comment]
Bonjour, il n'y a pas de cookie jusqu’à ce que vous appuyiez sur le bouton de lecture. Ensuite, l’utilisateur reçoit des cookies, sans consentement.

**Comment by Brouilles** [comment]
Et il y a des cookies HSID, SSID, APISID and SAPISID. Qui, je crois, concerne du tracking.
https://cookiedatabase.org/cookie/google-ads-optimization/sapisid/
