### ISSUE TITLE
Contenu du bloc de code du markdown dupliqué

### ISSUE THREAD

**Issue by nitrzm** [Grafikart/Grafikart.fr#455]
Bonjour,
En postant une réponse, j'ai remarqué que le code que je mettait dans mon message en format Markdown était dupliqué.
Sauf erreur de ma part, j'ai bien écris le Markdown. 
Lien du commentaire : https://grafikart.fr/tutoriels/router-919#c56664
Voici les captures à l'appuies : 
![image](https://user-images.githubusercontent.com/73536802/188474354-80040f67-a140-4d23-88ba-b83697f97132.png)
![image](https://user-images.githubusercontent.com/73536802/188474393-2692d065-831c-4fdc-a3b0-1df92fc4de77.png)

**Comment by nitrzm** [comment]
PS: ça le fait aussi sur d'autres commentaires plus bas

**Comment by Grafikart** [comment]
Bien vu, ça ne le fait qu'en production c'est pratique :D

**Comment by Grafikart** [comment]
Fixed with 28fa40de9589a4adbb43bd2f2ee452a93ee3c6e8
