### ISSUE TITLE
Création d'une entité

### ISSUE THREAD

**Issue by aniskasmi** [Grafikart/Grafikart.fr#463]
Lors de la création d'une entité avec le do:entity Test 

Ce message est return

` [ERROR] Only attribute mapping is supported by make:entity, but the <info>App\Domain\Forum\Entity\Test</info> class uses a
         different format. If you would like this command to generate the properties & getter/setter methods, add your mapping
         configuration, and then re-run this command with the <info>--regenerate</info> flag.   `

Voici les versions : 

`"doctrine/annotations": "^1.0",
    "doctrine/doctrine-bundle": "^2.5"  - 2.7.1,
    "doctrine/doctrine-migrations-bundle": "^3.2",`

`
    "symfony/maker-bundle": "^1.0" - 1.48.0, `

Je pense que le MakerEntity n'a pas eu l'update pour PHP8.1

**Comment by skPink** [comment]
Fix avec https://github.com/symfony/maker-bundle/issues/1152#issuecomment-1186085238
