### ISSUE TITLE
Les confettis en fin de vidéo ne se lancent qu'une fois par rechargement de page

### ISSUE THREAD

**Issue by phiphou** [Grafikart/Grafikart.fr#484]
Les confettis en fin de vidéo ne se lancent qu'une fois par rechargement de page.

Si on suit plusieurs vidéos d'une même formation d'affilées, on a bien les confettis en fin de première vidéo.

Mais pas pour les vidéos suivantes.

Si on recharge la page, ils reviennent, mais pour une seule fois.

Je suis en mode premium.

**Comment by Grafikart** [comment]
Je n'arrive pas à reproduire (et vu que ce n'est pas un pb grave je ferme l'issue désolé)
