### ISSUE TITLE
Volume identique entre deux vidéos

### ISSUE THREAD

**Issue by phiphou** [Grafikart/Grafikart.fr#485]
ça serait sympa si il était possible de garder le niveau de volume réglé par l'utilisateur entre deux vidéos.

**Comment by bernard-ng** [comment]
Tu pourrais utiliser le local storage pour ça, 
Le fichier qui s'occupe du player se trouve ici : assets/elements/player/YoutubePlayer 

```

function onYouTubeIframeAPIReady() {
  // iframeId parameter should match your Iframe's id attribute
  var player = new YT.Player('iframeId', {
    width: 140,
    height: 105,
    videoId: 'tGzl_AB4poI',
    events: {
      'onReady': function (event) {
        event.target.setVolume(0);
        event.target.playVideo();
      }
    }
  });
}

```

Ce lien pourrait t'aider : https://stackoverflow.com/questions/37244505/how-to-autostart-youtube-video-with-low-volume-iframe

Ta PR est bienvenue 👌🏽

**Comment by Grafikart** [comment]
Le volume est maintenant synchronisé (dans la partie tutoriel) pour les lecteurs Youtube / HTML5
