### ISSUE TITLE
Erreur dans les dates de commentaires

### ISSUE THREAD

**Issue by prbaron** [Grafikart/Grafikart.fr#487]
Il semblerait que les dates de commentaires soient incorrectes. Il n'est pas possible d'avoir un commentaire plus ancien que le post associé.

![CleanShot 2024-04-11 at 11 52 26](https://github.com/Grafikart/Grafikart.fr/assets/1153856/680e8e54-c3ce-4429-aef4-e38dd24a9250)

D'après ce que je vois dans la console Chrome, il semblerait que le composant <time-ago> fasse son travail correctement. Le problème viendrait donc de la date enregistrée en base de données.
![CleanShot 2024-04-11 at 11 54 50](https://github.com/Grafikart/Grafikart.fr/assets/1153856/505132d6-b191-4b7d-843e-7dcd56b8a4ca)

**Comment by bernard-ng** [comment]
@prbaron Il s'agit d'un ancien tutoriel mis à jour, la série Sécurité des applications Web dans son entièreté est en train d'être mise à jour. (il aurait dû utiliser la fonctionnalité « deprecated by », pour une raison ou pour une autre, ça n'a pas été fait).

hint : tu peux voir les ID des tutoriels.
