### ISSUE TITLE
Problème avec l'affichage des icones SVG avec <use>

### ISSUE THREAD

**Issue by LiegeoisJules** [Grafikart/Grafikart.fr#491]
## Les icones en SVG ne s'affichent plus.
<img width="865" alt="1" src="https://github.com/Grafikart/Grafikart.fr/assets/1833927/3b6d2faa-dafc-4757-beeb-cc9873e333de">

Dommage j'adorais cette technique :(

**Comment by Grafikart** [comment]
Pour donner plus de contexte, il est apparu que le problème venait d'une mise à jour récente de chromium.
