### ISSUE TITLE
Progression, suggestion de contenu à la fin d'une formation

### ISSUE THREAD

**Issue by Grafikart** [Grafikart/Grafikart.fr#52]
Il serait intéressant de proposer des contenus à regarder lorsqu'un utilisateur complète une formation en lui envoyant un email ou via une alerte sur le site.

## Fonctionnement

Pour mettre en place ce système il faudrait créer dans un premier temps un système qui permettrait de définir les contenus "relatifs" à une formation (une liaison n-n entre Content et Content). Ensuite, il serait possible d'écouter l'évènement ProgressEvent et de déclencher l'envoie de l'email en suggérant X contenu relatif.

**Comment by YaFou** [comment]
## Problème
Je trouve que cette fonctionnalité serait une bonne idée mais je pense qu'une relation *n-n* serait trop compliquée à mettre en place sur le long terme : si pour chaque formation, il faudrait définir plusieurs formations liées, avec les mêmes points d’intérêts, cela pourrait devenir trop compliqué pour l'administration.

## Solution
Une solution que je pourrais apporter est d'utiliser un système de tags, ou les lier avec les technologies, avec lequel l'événement pourra automatiquement détecter les formations avec les mêmes tags / technologies et ainsi pouvoir proposer les formations qui n'ont pas encore été faites par l'utilisateur et qui sont relatives par rapport à la formation réalisée. Un système de cache serait le bienvenue !

**Tout avis sur cette suggestion est le bienvenue ! :smile:**

**Comment by Grafikart** [comment]
Vu qu'il y a assez peu de formations qui ont une suite. Je préfère mettre cette feature en standbye
