### ISSUE TITLE
Structure du forum, système de tags

### ISSUE THREAD

**Issue by Grafikart** [Grafikart/Grafikart.fr#54]
Les forums passent maintenant a une structures de tag. La question est donc de trouver une organisation convenable. 

Ma première idée est de séparer par langage et d'avoir en enfant les framework technos. Le souci est alors: comment dire "ma question concerne PHP brut"

L'objectif est d'avoir à gauche du forum une navigation permettant d'accéder rapidement au sujet qui nous intérèsse : https://discuss.flarum.org/t/meta

**Comment by ashikuri** [comment]
je pense qu'un truc de ce type serai bien:
✔️Javascript:
   Vue
   React
   NodeJS:
      Express
   Typescript:
      Webpack:
         Vue
PHP:
   Laravel
   Symfony

*Article sur le js*

enfin si tu vois ^^

**Comment by SwithFr** [comment]
L'idée d'avoir une organisation "à plat" sans notion d'enfant/parent reste à mon sens le plus simple. 
Quitte à avoir du coup un grand nombre de tag/technos dans la sidebare (qui pourrait d'ailleurs lister les plus utilisé et un petit autocomplete pour la recherche d'un tag en particulier) 

Ainsi on aurait pas de famille/catégorie "framework" mais directement Laravel, Symfony, Cake... et un tag PHP pour toutes question relative au PHP sans contexte de framework. Après en laissant la possibilité de mettre jusqu'à 2 tags par topic on laisse le choix à l'utilisateur de faire sa propre arborescence. Ainsi quelqu'un ayant un soucis PHP au sein d'une app Laravel pourrait mettre PHP en tag principal et Laravel en second. On aurait plus une notion de priorité des tags qu'une relation parent/enfant. 

Après, comme tu le disais en live, c'est pour ceux qui veulent aider en filtrant selon le tag. Par exemple un expert tout framework confondu voudra peut-être avoir la catégorie "framework". Mais c'est pas vraiment un problème au final car on peut envisager (et là bon courage pour le dev mais ça serait vraiment tip top) c'est un système comme gitlab avec la possibilité de recherche dans les issues comme ça : 

![image](https://user-images.githubusercontent.com/4257500/79013995-3ee27600-7b6a-11ea-9676-15063d7b1d80.png)

Ainsi chacun filtrerait comme bon lui semble ;) 

En espérant avoir été suffisamment clair dans mon propos !

**Comment by Spooky063** [comment]
J’aime beaucoup la possibilité d’avoir un système d’arborescence mais il faut qu’il soit globale sinon on perd en lisibilité et en recherche.
Ce que je te propose est simple ; un système parent/enfant sur 1 niveau max avec comme racine le langage et comme enfant les technologies (comme cela tu pourrais ajouter un lien vers le forum de la technologie sur la formation en question par exemple).

Cela ferait une arborescence simple de type : 
- PHP
  - Symfony
  - Laravel
  - Composer
- Javascript
  - Vanilla
  - TypeScript
- CSS
  - Sass
- DevOps
  - GIT
  - Docker
  - Jenkins

En ce qui concerne la création d’un topic, je verrais bien un principe ou tu peux uniquement choisir un tag enfant. Mais si le tag n’existe pas, la personne va vouloir associer son topic au parent.  
Donc soit tu offres la possibilité aux utilisateurs d’ajouter des tags 😄 (avec la possibilité d’avoir n’importe quoi en front), soit tu fais la liaison comme Flarum ou tu peux cocher le parent qui fait apparaître les enfants. Dans tous les cas tu peux persister uniquement le tag le plus profond.

Après si tu comptes ajouter un système de recherche, tu peux ajouter un champ `related` sur les tags qui permet de faire une liaison avec plusieurs keywords (tags qui n’ont que vocation à être recherchées et non associé à un topic).

On aurait donc par exemple : 
- Composer
  - parent : PHP
  - related : php, CI, gestionnaire de paquet, packagist

**Comment by ashikuri** [comment]
> L'idée d'avoir une organisation "à plat" sans notion d'enfant/parent reste à mon sens le plus simple.
> Quitte à avoir du coup un grand nombre de tag/technos dans la sidebare (qui pourrait d'ailleurs lister les plus utilisés et un petit input autocomplete pour la recherche d'un tag en particulier).
> 
> Ainsi on n'aurait pas de famille/catégorie "framework" mais directement Laravel, Symfony, Cake...(ce qui au passage retire un clic inutile sur la catégorie framework si on ne veut que du Laravel, on l'aurait directement en visuel) puis un tag PHP pour toutes question relative au PHP sans contexte de framework. Après en laissant la possibilité de mettre jusqu'à 2 tags par topic on laisse le choix à l'utilisateur de faire sa propre arborescence. Ainsi quelqu'un ayant un soucis PHP au sein d'une app Laravel pourrait mettre PHP en tag principal et Laravel en second. On aurait plus une notion de priorité des tags qu'une relation parent/enfant.
> 
> Après, comme tu le disais en live, c'est pour ceux qui veulent aider en filtrant selon le tag. Par exemple un expert tout framework confondu voudra peut-être avoir la catégorie "framework". Mais c'est pas vraiment un problème au final car on peut envisager (et là bon courage pour le dev mais ça serait vraiment tip top) c'est un système comme gitlab avec la possibilité de recherche dans les issues comme ça :
> 
> ![image](https://user-images.githubusercontent.com/4257500/79013995-3ee27600-7b6a-11ea-9676-15063d7b1d80.png)
> 
> Ainsi chacun filtrerait comme bon lui semble ;)
> 
> En espérant avoir été suffisamment clair dans mon propos !

ça veut dire que si je demande le PHP je ne dois pas avoir Laravel ou Symfony car c'est déjà une catégorie à elle seule?

**Comment by SwithFr** [comment]
@ashikuri c'est ça ! Pour moi, si ta question porte sur du PHP, seul ce tag t'intéresse, si c'est lié à Laravel (ou autre) bah tu as un tag dédié, autant l'utiliser ;)

**Comment by Grafikart** [comment]
Maintenant que c'est en ligne je ferme l'issue. Les tags ont été mis en place ;)
