### ISSUE TITLE
Forum import fail

### ISSUE THREAD

**Issue by Louzet** [Grafikart/Grafikart.fr#57]
Lorsqu'on lance la commande make import, on obtient cette erreur:

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'grafikart_dev.forum_forums' doesn't exist`

Dans le forum importer, c'est la ligne 28, qui pose problème:
`// On importe les tags
        $query = $this->pdo->prepare(<<<SQL
            SELECT *
            FROM forum_forums
        SQL);`

visiblement, la table forum_forums n'existe pas !

**Comment by Grafikart** [comment]
Import est une commande qui est destiné à l'import depuis la base de données courante donc il est normal qu'elle ne marche pas de ton côté. Utilise plutôt la commande seed pour remplir la base.

**Comment by Louzet** [comment]
J'ai essayé de créer un nouveau sujet dans le forum, et j'avais un problème avec le tag. ce qui m'a fait pensé que la command make seed n'avait pas importé les tags.
Jee vais mieux regarder, ça vient peut être de mon côté

**Comment by Grafikart** [comment]
Yep il n'y a aucun seeder encore pour le forum c'est tout à fait normal de n'avoir aucun tag ;)

**Comment by Louzet** [comment]
Ha, je comprend. Merci pour ton feedback, je close l'issue alors !
