### ISSUE TITLE
Vite failed to load config

### ISSUE THREAD

**Issue by Xonn** [Grafikart/Grafikart.fr#65]
Au lancement de docker avec `make dev`, j'obtient une erreur sur vite et du coup le container node plante

<img width="773" alt="Capture d’écran 2020-07-16 à 12 05 55" src="https://user-images.githubusercontent.com/12433170/87658722-def8fe00-c75c-11ea-936a-e59bb314ec38.png">

**Comment by Grafikart** [comment]
Tu peux tenter de faire un yarn et puis relancer pour me dire si ça marche ?

**Comment by Xonn** [comment]
Le container se lance bien, mais quand je vais sur `http://grafikart.localhost:8000/` l'inté ne s'affiche pas;

Dans la console chrome : 
<img width="1406" alt="Capture d’écran 2020-07-17 à 10 22 47" src="https://user-images.githubusercontent.com/12433170/87765020-90f50080-c817-11ea-8110-d9adc2d538fd.png">

et dans mon terminal, une nouvelle erreur : 
<img width="841" alt="Capture d’écran 2020-07-17 à 10 21 21" src="https://user-images.githubusercontent.com/12433170/87765041-9a7e6880-c817-11ea-896f-586f9923f89e.png">

**Comment by Grafikart** [comment]
Je refais un tour sur le site ce soir pour le beta 12 de vite je regarderais si je peux trouver la cause.

**Comment by Xonn** [comment]
Depuis les derniers commits, le problème semble résolu :)
Petite erreur JS dans la console chrome : 
<img width="1397" alt="Capture d’écran 2020-07-23 à 11 08 13" src="https://user-images.githubusercontent.com/12433170/88269739-e11b0980-ccd4-11ea-907b-3af5db3a4da1.png">

Par contre j'ai quelques lenteurs sur le site, mais c'est peut-être lié à la version mac de docker, j'ai vu que les perf n'étaient pas folle.

**Comment by Grafikart** [comment]
Oui docker mac est pas top du tout en perf :(
