### ISSUE TITLE
DESIGN : Live

### ISSUE THREAD

**Issue by Grafikart** [Grafikart/Grafikart.fr#8]

**Comment by crownbackend** [comment]
Il faut faire une pagination et un joli cadran pour récupérer les vidéos depuis youtube

**Comment by betaWeb** [comment]
Salut @Grafikart,

Je pensais que tu pourrais trier les lives par année : j'imagine un bandeau sous la vidéo avec des badges (qui reprendrait le design des badges de difficultés des cartes tutos, donc boutons arrondis) représentant les différentes années, et qui permet de filtrer selon celle(s) choisie(s) (avec possibilité de tout afficher avec une simple pagination `Prec.` et `Suiv.`). 
Concernant la disposition des lives, pourquoi pas une simple table striped et hovered (oui c'est très bootstrap-esque, mais on se comprend ;)) avec le titre, la date, et peut être sur la droite la ou les technos principales associées au live le cas échéant ?
