### ISSUE TITLE
Complément à PHPstan

### ISSUE THREAD

**Issue by Mcdostone** [Grafikart/Grafikart.fr#90]
j'ai fait tourné deux outils d'analyse d'analyse disponible gratuitement pour des repositories open-source: **sonarcloud.io** et **scrutinizer-ci**.

Les résultats sont disponibles publiquement:
 - https://scrutinizer-ci.com/g/Mcdostone/Grafikart.fr/
 - https://sonarcloud.io/project/issues?id=Mcdostone_Grafikart.fr

Leurs mises en place est très simple. J'ai regardé en diagonale les résultats, ceux de **scrutinizer-ci** me paraissent plus intéressants.

**Comment by Grafikart** [comment]
LEs règles sont un poil trop stricte pour le moment. Je referais peut être un tour sur tout ça après le déploiemlent.
