### ISSUE TITLE
tests unitaires erreur fixtures

### ISSUE THREAD

**Issue by oussaka** [Grafikart/Grafikart.fr#95]
Bonjour,

Il y a un comportement bizarre avec les fixtures qui font planter les tests!
Quand on lance cette fixtures on est censé avoir 5 lignes en base de données mais pas 15

``` 
// tests/fixtures/comments.yaml:10
App\Domain\Comment\Comment:
  comment{1..5} (extends comment):
``` 
mêmes choses comment{1..10} ajoute 110 ligne etc (les deux points sont ignorées)... 

D'où le fail des tests U.

``` 
vendor/bin/phpunit --filter test* tests/Domain/Comment/CommentTest.php
1) App\Tests\Domain\Comment\CommentTest::testCascadeDeleteForUser
Failed asserting that 2 matches expected 3.

/var/www/tests/Domain/Comment/CommentTest.php:55
```

**Comment by Grafikart** [comment]
Je laisse l'issue ouverte car je remarque que les tests plantent à ce niveau là. Je regarderais si c'est à cause de ce que tu as signalé.

**Comment by oussaka** [comment]
ce bug n'est plus d'actualité!
