### ISSUE TITLE
Initialisation du projet

### ISSUE THREAD

**Issue by jvancoillie** [Grafikart/Grafikart.fr#98]
Lors de l'initialisation du projet, le [README.md](https://github.com/Grafikart/Grafikart.fr/blob/master/README.md) nous dit que pour participer on peut lancer le serveur avec la commande "make dev" or cette commande ne suffit pas à initialiser le projet. Il est nécessaire de lancer un make install pour générer les assets. serait-il possible de détailler un peu plus le process d'initialisation ?

**Comment by jvancoillie** [comment]
une modification de la dépendance de "make dev" fonctionnerait-elle ?
`
dev: vendor/autoload.php node_modules/time## Lance le serveur de développement
	make -j 2 server
`
par 
`
dev: install## Lance le serveur de développement
	make -j 2 server
`

**Comment by Grafikart** [comment]
Bonne remarque j'essaie de regarde ça dès que possible.
